controller:
  watchIngressWithoutClass: true
  hostNetwork: true
  hostPort:
    enabled: true
  kind: Deployment
  service:
    type: NodePort
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
  admissionWebhooks:
    enabled: true
  nodeSelector:
    router: enabled
  tolerations:
   - key: "router"
     operator: "Exists"
     effect: "NoSchedule"
  updateStrategy:
    rollingUpdate:
    type: Recreate
defaultBackend:
  enabled: true
