controller:
  watchIngressWithoutClass: true
  hostNetwork: true
  hostPort:
    enabled: true
  kind: Deployment
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: NodePort
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
