controller:
  watchIngressWithoutClass: true
  hostNetwork: true
  hostPort:
    enabled: true
  kind: Deployment
  service:
    type: NodePort
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
  admissionWebhooks:
    enabled: false
  nodeSelector:
    router: enabled
defaultBackend:
  enabled: true
