controller:
  watchIngressWithoutClass: true
  hostNetwork: false
  hostPort:
    enabled: true
  kind: DaemonSet
  service:
    type: NodePort
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
