crds:
  enabled: true
defaultRules:
  create: false
alertmanager:
  enabled: false
grafana:
  enabled: false
kubeStateMetrics:
  enabled: true
prometheus:
  enabled: true
  prometheusSpec:
    secrets: ['etcd-client-cert']
    retention: 14d
    retentionSize: "10GB"
    resources: {}
    # requests:
    #   memory: 400Mi
    #   cpu: 200m
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: hcloud-volumes
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
prometheusOperator:
  enabled: true
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
kubeEtcd:
  serviceMonitor:
   scheme: https
   serverName: localhost
   insecureSkipVerify: false
   caFile: /etc/prometheus/secrets/etcd-client-cert/ca.crt
   certFile: /etc/prometheus/secrets/etcd-client-cert/server.crt
   keyFile: /etc/prometheus/secrets/etcd-client-cert/server.key