crds:
  enabled: true
defaultRules:
  create: false
alertmanager:
  enabled: false
grafana:
  enabled: false
kubeStateMetrics:
  enabled: true
prometheus:
  enabled: true
  prometheusSpec:
    secrets: ['etcd-client-cert']
    retention: 14d
    retentionSize: "10GB"
    resources: {}
    # requests:
    #   memory: 400Mi
    #   cpu: 200m
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: hcloud-volumes
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
prometheusOperator:
  enabled: true
  tls:
    enabled: false
  admissionWebhooks:
    enabled: true
kubeEtcd:
  service:
    enabled: true
    port: 2381
    targetPort: 2379
  serviceMonitor:
   scheme: https
   insecureSkipVerify: false
   serverName: localhost
   caFile: /etc/prometheus/secrets/etcd-client-cert/ca.crt
   certFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.crt
   keyFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.key