# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1771159493  nanos:699501039
#   expiresAt: seconds:1802695500
#   id:        ab17a2ff-d49e-474d-8244-209d81735af9
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZjCCAk6gAwIBAgIJAI2nqzSpWVSXMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNjAyMTUxMTQ1
            MDBaFw0yNzAyMTUxMjQ1MDBaMIG8MS0wKwYDVQQKEyRhYjE3YTJmZi1kNDllLTQ3
            NGQtODI0NC0yMDlkODE3MzVhZjkxIjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9M
            X1NFUlZJQ0UxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAw
            MDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTAy
            MDczMTUzMjMxMjYzNzE0NzkwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQbOlmr
            l1KuuIjEjtt6VgNCKgSvXhxPTl+6EWokOkUcK3DtQTEhJmzTFGfrURuxhECYxIyU
            ISDRICzgGK157h94o4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
            BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUD1f/DqQh
            XiQ26IhwqJkZq2kQcK0wHwYDVR0jBBgwFoAU5JwhyoGJIpw4wMwuCO/bfqHe0RYw
            RQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lv
            bi1jb250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEADVJhG2hC
            RR5gHw8bTkYUPqR346IHd1itczQ8o7wmX0A0VmykzjySeBqOuxgQqcKSbvydWkWS
            3SZl1F5o5+/R7RZK0AfkkyHRGJZCsqOf6vajwLEQHi1HBm3SeA47UovXTV84pqlW
            p7wGFmaGV3wdEL1U0F1QQNmsjP7yPEDM5qhfkOCvHKzashfo9mZWuLu3k4opag4/
            buRJX+63g5QNaxN7KMLJSDhVsdNZbyQ0d+av2KGVoZB8ai8Ss2XA2Y8bw1+BhuUz
            A5doEzPZ0uQy/1FI3+RIu/e+6OyV4PD9eBYEK+IG/zssHX2qkgHHy+1UWSR0O/yE
            BgVj9JtNIXA+EQ==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIKZWOUxKx36bIud0MVkj9Qe4oLCHw5LzkvQ5AEqKMhUyoAoGCCqGSM49
            AwEHoUQDQgAEGzpZq5dSrriIxI7belYDQioEr14cT05fuhFqJDpFHCtw7UExISZs
            0xRn61EbsYRAmMSMlCEg0SAs4Bitee4feA==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRAKqh7zUtR4DzasD1hGo7pycwDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2
        MDIxMzEzNDMwMloXDTMxMDIxMjEzNDMwMlowKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEAmeMdP9MeofxKLzdBAv67veXldqTAn356x+PI8juIoCrKzY1QOgtd5liW
        U8U1nBcYeGpgiEXNhJJijwncQlhMRgGq1k/P2KGW+WVb49kESeRYrCXw056GWi2Y
        wbM9y3pWvV/wIZsQR9lDXGJ9PaC0RAjm6GqLKbn4YKYlZMUQqbHGE3k8PW1dHys9
        jHrkoYjblI2lf3gBmNVUCkhZzFYDoy1E6DnVBbXy8qGSaIdiFzdIZlhF9foZ1eeo
        aICQlTuB0C8ijVmukYCpTBIyo6hCeWRJcoKYiAC1m2iU3PA5hnAaAiMmhAT+58SI
        fEWCeahn6cqXlHvHH0x6rLYjakOu8wIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFOScIcqBiSKcOMDMLgjv236h3tEWMA0GCSqGSIb3DQEBCwUAA4IB
        AQAp2dnAZ3Q0BW105wZ1K1v3KBCVpgjqTVBXney0/D3c9wcoC7YyuzOziickMdzb
        Iz0+YQ5TCSYfMpVNhbrZ/BBfEJU0QWlzf7KKvfRT3Grt8IhZVsRkjucWQIKyYAlQ
        7nQiGJiWhZ+fEIiRCLIFDHXQ5Na6rnTq1TwhrzQ4OuWuSIzrUz5+aExES7nidVLL
        DHp3O3Lvc1GGoW3sakQCGV73RLtZ8PygGLvs7qzi4JnJxZVxEWU9L5Md3/AWblQ7
        KOES+3CQ4SfP01Dpy8/iGpQdQVAOtMKYsIx/qtQMlXLlNyPX0rkvSAVi8jc46VEz
        A8k+tEqpn6nb4hoVZvavBhNn
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIIObod09YDYM8wDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2MDIxNTExNDUw
            MFoXDTI3MDIxNTEyNDUwMFowgasxLTArBgNVBAoTJGFiMTdhMmZmLWQ0OWUtNDc0
            ZC04MjQ0LTIwOWQ4MTczNWFmOTEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzQxNTk2NzAwMDE0OTU5MjQ5NDMw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQZs+ZrR6OcIkh4YyJWiy9jjrAo1ypp
            PB+xr2BugKK1lquh30aJXdL1ZgIVBuODkQgt4zVf/K5+6scbLxnsTgBgo4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUjEpkiV+EsopYEO3eyzdw0KzgjiUwHwYD
            VR0jBBgwFoAU5JwhyoGJIpw4wMwuCO/bfqHe0RYwNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQB4SWCKzoudSALUiLQNF7pEaAH64vTq2MICjvtAo/PKMkt/gRMspNYI
            7gUkXOlQhWjjs7rQs3Xp+7IAiUbZuPlytzu6HIcgi2ioCn+BEQNU67n+nkCLmoaZ
            uRAqTomwqFgCkWg/ZiLSI2UTPScISSJmIK98FU34pTCJKx46ZB4hVZuwfacAQwSE
            9mvF26EGrn1ipepQFGywPH2yHN02Yxw384ZKJHz6H8Kqe1yJf24sqsWRfRP9XMjw
            2xmYEnhKPRRdPMR2OvhLEXlS9x57S0WExwoTqgGLm9O3O4DGD1DWTGAcbEuNuLcF
            axDagKZHH0pzCukppHpwHQGa2mFGtfBB
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIJz4ADs90YhqSHiUA8kTBFyUXmr47CCZG4fNilj3RB/1oAoGCCqGSM49
            AwEHoUQDQgAEGbPma0ejnCJIeGMiVosvY46wKNcqaTwfsa9gboCitZarod9GiV3S
            9WYCFQbjg5EILeM1X/yufurHGy8Z7E4AYA==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVTCCAj2gAwIBAgIIPwY/kkEwnpcwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2MDIxNTExNDUw
            MFoXDTI3MDIxNTEyNDUwMFowgaUxLTArBgNVBAoTJGFiMTdhMmZmLWQ0OWUtNDc0
            ZC04MjQ0LTIwOWQ4MTczNWFmOTEXMBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7
            BgNVBAMMNFNFTlNPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0w
            MDAwMDAwMDAwMDAxHDAaBgNVBAUTEzQ1NDEzODcxNzE2NDEyMDQzNzUwWTATBgcq
            hkjOPQIBBggqhkjOPQMBBwNCAAQPNCHrAylIC1dgQ/p+z+FPeohf+Ao83qYKQQ49
            ND1uiyqgqlydS5QclarEvzAoPn43zkwAXUXtduV4/RNUtAxao4HOMIHLMA4GA1Ud
            DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
            AQH/BAIwADAdBgNVHQ4EFgQUCh3gFt+4afoIE0eRWGLRkSbIBWQwHwYDVR0jBBgw
            FoAU5JwhyoGJIpw4wMwuCO/bfqHe0RYwTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNr
            cm94ghNzZW5zb3Iuc3RhY2tyb3guc3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3Jv
            eC5zdmMwDQYJKoZIhvcNAQELBQADggEBAJKzb0oUPidqkA4rl0mEX4eirGEhccNb
            Gyf3m5Mz0/sSQO0wU/MdP6hbb1u6DtYilxBOa4R9zWZmWqDnxcI82AzeHkOIx7j8
            bByXSly0Ir0boSfzORwQSmDMGjxDPPiZaAd4ZuRHhiLXPOC4LbiB9pxoNGsYeP+p
            25WpEHi57KAj/Yza0447GQfnXqQHqEtsBBtsAiM55nvfhFz2qXLz6KuLDPyouCWy
            4FImaKHRz2A+flwBdWekfhN+fRDQlv60UkCK241JH6USjreHp2h99g+BkVUAaYOQ
            CUxNgnZCAgTYJvyi/2TvD2GOd1FVz8avYmRIvnMAwRUOVBoMfuyZ0KQ=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIAkcE5c2u35Y6g+WCiPbIJbbvOH1Aa6PFeuguA+mh3r3oAoGCCqGSM49
            AwEHoUQDQgAEDzQh6wMpSAtXYEP6fs/hT3qIX/gKPN6mCkEOPTQ9bosqoKpcnUuU
            HJWqxL8wKD5+N85MAF1F7XbleP0TVLQMWg==
            -----END EC PRIVATE KEY-----
