# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1746819878  nanos:131931391
#   expiresAt: seconds:1778355900
#   id:        e2603b9c-9e09-4cd7-ba28-15375e602b63
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZjCCAk6gAwIBAgIJAM9ydwJ7ttHoMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA1MDkxODQ1
            MDBaFw0yNjA1MDkxOTQ1MDBaMIG8MS0wKwYDVQQKEyRlMjYwM2I5Yy05ZTA5LTRj
            ZDctYmEyOC0xNTM3NWU2MDJiNjMxIjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9M
            X1NFUlZJQ0UxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAw
            MDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTQ5
            NDgxNDA5NjU3NDUzMTYzMjgwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQehtnn
            rPbvobNtBMONhSKp+jFXSFOHu07myLNWPuxiEze9aivGELxCnWpl516u4lgLOVQ2
            J3IawlWJ4qwVBMPso4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
            BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUGkzEOLPp
            ExGfbrMxcY+J9UVNtC4wHwYDVR0jBBgwFoAUneci6YjsY1s0rNpPAQXxAokLTIIw
            RQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lv
            bi1jb250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAipDaN9qr
            e4rQGM6eRv/CL1JOU8z/Z42+JdKqZ2WIxJjltDkBNq08BzzS7RNsKK6OJTWGLfR8
            wVzr5Xy4m+mWBkzjcWbRuOkm69E7tj/h3NIKjxFJwYI3rqOHETuHGb3mCkbFKt7+
            4o0S5Ai2gqm881kQqd/6uBmcQyOzLkPzvpRrk5DHbhDB9oReo7ogWxtNPYwXbpD9
            ybRQixx/TL2HEdPeNI7ekVOEM47E+gPoqLYieVyRtnKtwlWA8UNhnemuS0oV94pq
            O5U9a52bpXHeWlIFV2iN/tBSbJ4D+TIVgrCBF6Npz1IcQlIgyQITZkGzVvWLU9dl
            M09SpbmL+IiCLw==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIBWkSKBzXycUySavAkDKnJKrWTBBFD3i/LCofNFxwFreoAoGCCqGSM49
            AwEHoUQDQgAEHobZ56z276GzbQTDjYUiqfoxV0hTh7tO5sizVj7sYhM3vWorxhC8
            Qp1qZederuJYCzlUNidyGsJVieKsFQTD7A==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRALAOajvAX5U/XznXRYsGaf0wDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1
        MDUwOTE5Mzk1N1oXDTMwMDUwODE5Mzk1N1owKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEA1DDEDI+aMYfZ7M0qYvPN4FjXW3Gxy0bVwoWL63+VTqD3t7uf1u0wRQ1u
        qi276LMhdguhKW5dQ/geUdqxmDC8qe6Fre7OteYmAc7P3ujeYzcSbE1wqGA3wg4c
        hNW+ThjKF5Q++Xzo1eQ2ssN00YrS05TxnNNU6eRDsZZi3NI6MI8ER2pjZ6uKcu58
        v80vmIrTEwQTdBwG+lW/POGWpJe05RW71UA3kvZxFV16RdRvLUD0TtmkLadaQn4X
        udtWtF1il1Q5xxkdWA7FxvMi+akqfys7xGTnFlWMksdOgXyF1fiH1TJo/cF3iJWh
        lOdw3GgIrvprr+vah4sl8p+bFO8POQIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFJ3nIumI7GNbNKzaTwEF8QKJC0yCMA0GCSqGSIb3DQEBCwUAA4IB
        AQCEPGv/l7Yq9a9DKuMUHu8qAGIPhQYRVZ23MJuMeClgOixlFyjP+9LWGVRakDEP
        kjhDCGSZ8lqgEhF9DGFZ794Rn7hWcq3XuwiaQXacy1WXJYR2IhmcQO+1jKSXMf4P
        2uqSlQ/57ltgdAsE+VNCnDNSokP8e1TWBD8iuwJFw0Xh3R+FP9DciacheBppE+5Q
        D1I0aD6uYINNzPV3DLWiVPLGxCABLR+jOCJDv8ccZ06r9zHRR86SqLJMSGzxAbSr
        o9cD1fvV4UkO875xK0giV0g1696KxpNWfFGDOYrs7GrARH6Zt4B2HGMn7nDm8zAZ
        ssm3cdzzro4umRryLngJUz07
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRjCCAi6gAwIBAgIJALnSq1lqG0g4MA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA1MDkxODQ1
            MDBaFw0yNjA1MDkxOTQ1MDBaMIGsMS0wKwYDVQQKEyRlMjYwM2I5Yy05ZTA5LTRj
            ZDctYmEyOC0xNTM3NWU2MDJiNjMxGjAYBgNVBAsMEUNPTExFQ1RPUl9TRVJWSUNF
            MUAwPgYDVQQDDDdDT0xMRUNUT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAw
            LTAwMDAtMDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxMzM4OTk1MzA0MjY0NjUxNzgx
            NjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCeP/z4dK5OcrDgvBUgSZnkpNyH8
            f1ypEwTnoe7rNf292cJKZXAFgYNX2r1BoYJAy9D03fV+p7GY4PHoDU3TN5Ojgbcw
            gbQwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
            AjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTBXpZsCFYtZ17VchAk31gq1xvjHDAf
            BgNVHSMEGDAWgBSd5yLpiOxjWzSs2k8BBfECiQtMgjA1BgNVHREELjAsghJjb2xs
            ZWN0b3Iuc3RhY2tyb3iCFmNvbGxlY3Rvci5zdGFja3JveC5zdmMwDQYJKoZIhvcN
            AQELBQADggEBAEvFKP6kcWVYAqQLxd0BJmyKXE0roY6OhOL67eIAHhnlqLM/iqkR
            VDj6rjtQbV3Ln18u0MKVU6zsNSLXwo4FtoNXm6QaFwnLKg7YDufTyB516tysCSAZ
            YdGHQKyt17i7ZSNlWyci2Y3JMk/GmFIfpdRHJcO9KbN7i9EPeqg7muc6D2CFg7L3
            PY9SlZpXBgA5FYas8FGiCJxckYjuVccf5oqufmyYCAzgtccUMhtPK/UXzM26HZNz
            4OInNf2bmpucH5KCnbZBpwYGO3EhumvZhw2yTg+cgQSXnZ8OTItEudQXg8RFYshO
            I2yD+SDYFUv+UA+/4ERiZSyBpQVeaxD8o90=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEINwt9Y126yeS7/+1PhwOpuxJiycn33Wv6W+oMMwAOUZ5oAoGCCqGSM49
            AwEHoUQDQgAEJ4//Ph0rk5ysOC8FSBJmeSk3Ifx/XKkTBOeh7us1/b3ZwkplcAWB
            g1favUGhgkDL0PTd9X6nsZjg8egNTdM3kw==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVTCCAj2gAwIBAgIIMrGRnGIm6f8wDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDUwOTE4NDUw
            MFoXDTI2MDUwOTE5NDUwMFowgaUxLTArBgNVBAoTJGUyNjAzYjljLTllMDktNGNk
            Ny1iYTI4LTE1Mzc1ZTYwMmI2MzEXMBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7
            BgNVBAMMNFNFTlNPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0w
            MDAwMDAwMDAwMDAxHDAaBgNVBAUTEzM2NTI4NjA4NzM2MjE4MjYwNDcwWTATBgcq
            hkjOPQIBBggqhkjOPQMBBwNCAARYQy/ZPKyyxRqTTKRAK87z+EcfNK/6+xRn18xc
            8i2kECgyLjKgQZ7CZkpHs1Q7EDZeJx4x8j9gF5tmUGDkTI0Yo4HOMIHLMA4GA1Ud
            DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
            AQH/BAIwADAdBgNVHQ4EFgQU5Dy+Dpmgayf8MBUVwNCPibIwGTwwHwYDVR0jBBgw
            FoAUneci6YjsY1s0rNpPAQXxAokLTIIwTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNr
            cm94ghNzZW5zb3Iuc3RhY2tyb3guc3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3Jv
            eC5zdmMwDQYJKoZIhvcNAQELBQADggEBAEzs4ktr4NSJkFnHtDdSc3PPM5BnzdSe
            wq6xitmgbHuTHkoinNXiQxyMLOmAMdwxvRRWDVB7eDbaIdexLXJgwO2cFinqdogb
            KIiiDk+dn8Or1CAHd0q2wRsIZOLZI5+rkiN0hGYKj3oafQ1oVrlT+xcq9TaGTBAa
            zzMT9BcvlZpl1Hw2XYltAPWelo0XTDtAKiatqfvLOcIGyZyo1ar83i/dznviwHHJ
            pn3Z8/J3/M+57yZ2q/jsPxB+/R5wGC5Mtaqz3ovPc1v62EGiq3b1pCliQyfTYWua
            3IKrIRLrQ+J4VnjlikbcdnqjCIDuVAkWRtKCxaoemC30ySTVKYhXjZ0=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIGtpA6pNrdne4OsPHUgLGDk47t7JpLf5rud/JmRpriPBoAoGCCqGSM49
            AwEHoUQDQgAEWEMv2TysssUak0ykQCvO8/hHHzSv+vsUZ9fMXPItpBAoMi4yoEGe
            wmZKR7NUOxA2XiceMfI/YBebZlBg5EyNGA==
            -----END EC PRIVATE KEY-----
