# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1733351066 nanos:659718935
#   expiresAt: seconds:1764887040
#   id:        91136301-c4be-4422-81f1-df1cbf4bc4c2
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDYzCCAkugAwIBAgIIC6jRe2FxI7MwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI0MTIwNDIxMjQw
            MFoXDTI1MTIwNDIyMjQwMFowgboxLTArBgNVBAoTJDkxMTM2MzAxLWM0YmUtNDQy
            Mi04MWYxLWRmMWNiZjRiYzRjMjEiMCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xf
            U0VSVklDRTFIMEYGA1UEAww/QURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAw
            MDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMRswGQYDVQQFExI4NDAx
            NTE2NTgzNTA1ODQ3NTUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ2r2wiLFD/
            tUaWhgigJQAGSq5tMCrUPD12VECHFrv9JjtiMOKnU0vXVBguSo4xFjjknFTDSGtm
            f7CgsenPvcXHo4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF
            BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU2tgaPvwAdTCF
            zn38yyDGJXO3NLUwHwYDVR0jBBgwFoAUJ8OGUCjU07/Y792o6Kvg1U7v1qswRQYD
            VR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lvbi1j
            b250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAVYY2xalBuRHN
            AZk+wYKqHyeKnzGfzLBn5NHI3+/RnDqqQ1z/mI7ZhARVWS/+hpH+1XoWjTbi2cKz
            YjrvvG5x0uMJ/nOEDtuaFMXBQRuqVW5/Lwr1nJtIGmhnXi62BhpoyaYAfQynxm0a
            WzxTjrUxj3/fK8L/U2pxgISFNupVUSr5+8FB0vc1nMoTw0DCE5/sbcyYuU+CCpgQ
            FS8Vmf3h1+x8suMuUcpAkZPs4bM9p2eZvtYB26A2RFcE098ol3OHp4eKY/GzM9tI
            CLwc0UAUpjsWB8VvVlyLpHdyjDjhbZfIO1itN3mtIQxPWpDrr8IGD5g+zdRAlvHM
            5cQot+S2eA==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIM9DMZjrOL9g/drT19U/ulOh9XvBDViRmFcWEXxBneLgoAoGCCqGSM49
            AwEHoUQDQgAENq9sIixQ/7VGloYIoCUABkqubTAq1Dw9dlRAhxa7/SY7YjDip1NL
            11QYLkqOMRY45JxUw0hrZn+woLHpz73Fxw==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPTCCAiWgAwIBAgIQd3DTT7O3+DT/95PKS/B7jDANBgkqhkiG9w0BAQsFADAp
        MScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjQx
        MjA0MjIxOTE4WhcNMjkxMjAzMjIxOTE4WjApMScwJQYDVQQDEx5TdGFja1JveCBD
        ZXJ0aWZpY2F0ZSBBdXRob3JpdHkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
        AoIBAQC6qymT57ZNgeucl4E9+zJ8vT45WM5eafWBTpz9u+S8pUFNWWSMbQUgGSq4
        APbKEL6VxXK6HciHIUr4gvXJlcKPmRAyLxK8E1lRB46kaL5TNQ+ku6fNLlray5gW
        pD23gAsQZK9srAMdeF+MXmO81soG5MwBGhaZgTUJNS9jskwAd2KltEFwx5hOSHBO
        C3JxUqNELxPTSqLBiUEX2Qxb2FfJ3/Pbzy13SiuRHKEFWeQ6bVYMi89swfNFGnY2
        2c1IkURyc68+My2dzsMvS0fvw9NV7iu7ayHS+kCq2r8R5LuZwwRl/OHRu+/t1Bx8
        +LRNQroaRHUAAgZNCCl/RZUc047xAgMBAAGjYTBfMA4GA1UdDwEB/wQEAwICpDAd
        BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAd
        BgNVHQ4EFgQUJ8OGUCjU07/Y792o6Kvg1U7v1qswDQYJKoZIhvcNAQELBQADggEB
        AK+cXF8mLCQKiROoP0MeE0lLm5k8LDao0TJG7UlxP5g1xWujOzbOKEwyqxlX2KQB
        lvK7Av7jeukkLCQgoaFrKeit6Z0MKo/b04ewjLDSafNnAOF4VIB8YGL0xWXWs/pu
        JVGn5S9v30PIOD3LNU/Yi6TKu3F2/GEMSdr3X7gum9ySOUupLYWYcUDFGRCPDXS6
        lnVzXlBrrVJDSWh2qX/mXyIoQ0ifIwW76LyjR0qUCUnt98RKcXLMKOuWU+jzWLXp
        OGT6cFLHfVJqPltfgiZ2jD8oLsL0JE++r3+gsLwVLG1e6j+O/+u19hBm4Sr1FfvY
        fXNWpIDR83i37b4ImD+HSvY=
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIIOe3kmz8f+JQwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI0MTIwNDIxMjQw
            MFoXDTI1MTIwNDIyMjQwMFowgasxLTArBgNVBAoTJDkxMTM2MzAxLWM0YmUtNDQy
            Mi04MWYxLWRmMWNiZjRiYzRjMjEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzQxNzQyNDM3ODUwNzI0NDE0OTIw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARfn2kzWl+RTdypJ+KxYyNhKb8pB7m/
            eun4tw6VAXTjpgxGtp5LW1YRd7ntqvkEuKJquzq/gQmOHTkKGp7F2S8go4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUYT5f4TmvwSVsSDBU8oANAKFVkrowHwYD
            VR0jBBgwFoAUJ8OGUCjU07/Y792o6Kvg1U7v1qswNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQBeOy/Fu9+1CjaDfmho6x75YiIX6MhaovjkkSqRNs/a9lH/joDAe5Xw
            TLMrRAnkJCpTohtErwpFbTudrbr761+xWBnq9rRmyUpdbxTe6A6aMpatFQrFYVFT
            LJ/5Oc/eJ8xHeXAUr10MLzzck2NAjyOZZL76AbABkmvyqLxJ0J7Aifg5YGoabx8B
            GeDmuEwo31BUT4Yl4b5ubWrBFcYhshYsUoP4bts0cHvedkdQWvVtbYMJiHBEDtTt
            3PAPY71QStDozRNDNpy1uFaLjOQQ5Ol/b2V7DbbtXg9UMb73WPE4saxUzvO+Wj/J
            00BltL5F3YPFcUoRUZpe+plRJJDCMb/9
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIEJ6U9SsQt/QEz5QdESuky5NphDTJSxI86mv9pjuf2+ToAoGCCqGSM49
            AwEHoUQDQgAEX59pM1pfkU3cqSfisWMjYSm/KQe5v3rp+LcOlQF046YMRraeS1tW
            EXe57ar5BLiiars6v4EJjh05ChqexdkvIA==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVzCCAj+gAwIBAgIJALLeKxC2FFNIMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNDEyMDQyMTI0
            MDBaFw0yNTEyMDQyMjI0MDBaMIGmMS0wKwYDVQQKEyQ5MTEzNjMwMS1jNGJlLTQ0
            MjItODFmMS1kZjFjYmY0YmM0YzIxFzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0w
            OwYDVQQDDDRTRU5TT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
            MDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxMjg4ODc4NjUzNDM1NTE5NDY5NjBZMBMG
            ByqGSM49AgEGCCqGSM49AwEHA0IABBZfyiacixDRrz+54cbrdpdHs74h9OeSOaea
            XK6ZFKYCvgTVaTfielXaRF6SCJrklBeDwj1YlfZ9Dri6lV9Qd02jgc4wgcswDgYD
            VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
            HRMBAf8EAjAAMB0GA1UdDgQWBBSPfXawJQfsYyylQWpjpFcktIKIlDAfBgNVHSME
            GDAWgBQnw4ZQKNTTv9jv3ajoq+DVTu/WqzBMBgNVHREERTBDgg9zZW5zb3Iuc3Rh
            Y2tyb3iCE3NlbnNvci5zdGFja3JveC5zdmOCG3NlbnNvci13ZWJob29rLnN0YWNr
            cm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAMMl9L/hLm6xmDOH61ULOCnqe9pnO
            yMg8mfr77CJ3yKPZ+v1vOsLM5kyzO35He9CrDURZCQb7JkZWhuQaceKvuNjAmbu7
            9J9TweBctmaBZq3Ejf6/FWXpxGzRIss3+2fw2DE90LKrycD9mMxfYQ+ydZnSC4aH
            gtKYIk3wojrk9CXjieocmMe6Kx8pWOXzjyGz137hwIaPCBoPVmbrQaIBGN6Wb1D7
            NYVmPedVzh2vjTB8a6ajkkR6Eaba5L3hyaLYXH1Jj2fVekce7deM/lIZ+1w8ah4t
            6cisTcr7m5X9RCrlzY0bPyMkWzf60gq80bb2Wtz2XzKZCod/B4om3h/lRA==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIHvyW80UN9I5xBuDAU2TtJASsmt0AbbsK+0Qj94/vpUfoAoGCCqGSM49
            AwEHoUQDQgAEFl/KJpyLENGvP7nhxut2l0ezviH055I5p5pcrpkUpgK+BNVpN+J6
            VdpEXpIImuSUF4PCPViV9n0OuLqVX1B3TQ==
            -----END EC PRIVATE KEY-----
