# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1771258589  nanos:443193290
#   expiresAt: seconds:1802794560
#   id:        3a3f6e21-0761-43ad-a393-9248b6ada104
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZjCCAk6gAwIBAgIJAKyTr8HgPSNyMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNjAyMTYxNTE2
            MDBaFw0yNzAyMTYxNjE2MDBaMIG8MS0wKwYDVQQKEyQzYTNmNmUyMS0wNzYxLTQz
            YWQtYTM5My05MjQ4YjZhZGExMDQxIjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9M
            X1NFUlZJQ0UxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAw
            MDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTI0
            MzU0NzYyNDMzMjU3MjM1MDYwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASw3LYW
            l0UfIBTs2F+sJMN58X6XgdKXpYIVi6ptWSAEpNyYnGXBF0Bldpe5qXMBUG5g5y+u
            zLtns5BqL9c59dYno4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
            BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU7vnxe3tQ
            oBhOrdav/jl4yqUyIXwwHwYDVR0jBBgwFoAU3SFMMCryO8h1/K7mmImxCwvkyJcw
            RQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lv
            bi1jb250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAXmc9jgba
            gKNTfTxh6g42juP2hbl1xEOSzHwbFu3dnkdGTCFlBHk/0Sg+yCq77CTwOj1rwg5T
            yHbQIudl5nTVxMyUp5XCHRdhl8VLEpmzIICJ5CZ7L1sQGX63RGWzf8Y+9S1jjFh8
            jKUM/o0NVnRJq5mj+n7uS+M2zv5RiS8bby8KybuPbqY00mnQDSztoKL+HOrPHezR
            cPO6JMUverbPJ8osKpsM0aCdaO84Ih9aqquUihz0hoRPLZ5gXtuS606sFNUoT0gS
            Q+nUOkjig45zAlPHcRakO+qUJt/qHkyE7L9/PN/vFdMKMHQ5ddFwNFGERrqmGZTQ
            QlVoWeFLaBDN3A==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIFVzvnMtl3JiZmPP9O3olhHwtpYOKsJO8rmb3guJ6Pq9oAoGCCqGSM49
            AwEHoUQDQgAEsNy2FpdFHyAU7NhfrCTDefF+l4HSl6WCFYuqbVkgBKTcmJxlwRdA
            ZXaXualzAVBuYOcvrsy7Z7OQai/XOfXWJw==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRAPoBYvvsYqJtIyGfwh5vPoMwDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2
        MDIxNjE1MzM0N1oXDTMxMDIxNTE1MzM0N1owKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEAxazurhQheNi4kvMWcubNrw1WjccSzMjNm850wDKJz218M7MiEcOE0gEU
        WRaiv8VTtHIN7dNm68mqo3Y3fpbgRbWJp32LuyUV86KLsVJIOYxm1xGsZS44W9bB
        Emy2z8svr9L3Gvzgqss4A/iBBHF9kt4d8t6H/hOSLcRdvMwRbz1A6eit7j5eoqnR
        FP2GiemL2YPrrNCzMixZbClnk4bS162C2zyVaauUfn6YBVnIz9HOWNVuvgiVBMSi
        2NjIkXNNJf49/3k/6PAt3dOr44HN7oPaP69ifisQGIffdBPmPwdeRM3LfsqVNHVy
        ck8XQaR6t2EANyO+oqhHT6vrmcHnJQIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFN0hTDAq8jvIdfyu5piJsQsL5MiXMA0GCSqGSIb3DQEBCwUAA4IB
        AQAXJsjIoyv+7s+2yqrRQ30hKqk6z16EU6yus9EHWBtzAEzffWueh9yZwRg7S6VK
        +FsS0/Ee8KIEqmkWNUwKLz4Dl7bBNiqnTZc/Av0hNX5us5xylGjFhh7b4SGBVEtb
        VtdTwPlRJqGidhPjxDg47KmJVJh1zHzs1T5fuJt/mboyykOZssfkjDrKI7ipR8JB
        GSBK1BHNwHR4e8dgPYnEEnKMjfWjuqxbc6jYamofO1Rzb4W8eBtZCQmxqMurMKGW
        sCXvw9gM5kho4sEaT259/jyDOwKVqLqFS2IAzkUGbsBNfJ4yezCkY4Qr+ZiNmsIb
        OPTPfccGie9Q3TdtyMb0FBCw
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIIZz16EJ2+4ykwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2MDIxNjE1MTYw
            MFoXDTI3MDIxNjE2MTYwMFowgasxLTArBgNVBAoTJDNhM2Y2ZTIxLTA3NjEtNDNh
            ZC1hMzkzLTkyNDhiNmFkYTEwNDEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzc0MzkyMzYzNzEyNzA1MjU3Mzcw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ+XPAsF3w54hfw1GCJ+lPP8sySjaNx
            fGYh9jJYrtNUzyM4yHse7H3YZB++AUycTBmqCQSpebS3qzij3yPrUlcho4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUNeLStlD+kchpXX8C84jlP1unN6wwHwYD
            VR0jBBgwFoAU3SFMMCryO8h1/K7mmImxCwvkyJcwNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQAue5y/zc3TCVfdCeYxIHBJSy5sxVeWn6uI/DCiUrVnxc/NLfxvxq95
            Oe04hQq+DQyxAhE0ATsrxiXIpeSu7d8+tzTAp4XtB/7D/Dh/0aIUHuA5A9ctPKhO
            HPWCU8m+KrYDuhOk41Fhh2Mtz4MS8Vy0AScohymZq+GLWKIv7goXs0b9Le5mnme3
            jRNlH1qdUq7euDpAthD8GQqxUSdvtq5WUZIXM9oN7ANJ4W8LYt0sMJYWl+9D19Qb
            i7IknipWIax4lJ3skT+AeUkvd+jGURRq00neOJ8bsbTVFhtJK/zTJEVgKjdtbyQs
            IV4FdvNf79RqnTW4KNYYVcXvOO1c8TeC
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIFnFsV2shvCaRLmYpsK9YYXh3X1lkFJv4m/kM44Cjz73oAoGCCqGSM49
            AwEHoUQDQgAEPlzwLBd8OeIX8NRgifpTz/LMko2jcXxmIfYyWK7TVM8jOMh7Hux9
            2GQfvgFMnEwZqgkEqXm0t6s4o98j61JXIQ==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVTCCAj2gAwIBAgIIREHJ/5dPIz0wDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2MDIxNjE1MTYw
            MFoXDTI3MDIxNjE2MTYwMFowgaUxLTArBgNVBAoTJDNhM2Y2ZTIxLTA3NjEtNDNh
            ZC1hMzkzLTkyNDhiNmFkYTEwNDEXMBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7
            BgNVBAMMNFNFTlNPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0w
            MDAwMDAwMDAwMDAxHDAaBgNVBAUTEzQ5MTg0MzQzNjc2NTc2ODE3MjUwWTATBgcq
            hkjOPQIBBggqhkjOPQMBBwNCAAS7zhpxpLyyZPoBGPTowDaDc0UuVVxUve8y7UgD
            2Du3fkzbQHvcazqoZ7kawknKfeYwIEGbaROg/0c9Dt1QR6tno4HOMIHLMA4GA1Ud
            DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
            AQH/BAIwADAdBgNVHQ4EFgQUnPP7AXtKjfrk9/WZRnwgtBmWpsQwHwYDVR0jBBgw
            FoAU3SFMMCryO8h1/K7mmImxCwvkyJcwTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNr
            cm94ghNzZW5zb3Iuc3RhY2tyb3guc3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3Jv
            eC5zdmMwDQYJKoZIhvcNAQELBQADggEBAABT5B7gNmwsiCaF85K72eSh94h/IS7V
            py2kiG1xSXQjDES+OQxA4pYRDImXeSg3djm948LrC7hBL+JKChjsXFelX8I2DX32
            l2UmN8haHaZACbUStpFjgwpSWJ2ao9h6EUahSIV3PKL+Z+0W9kUS4v8NaA8uhSVV
            amh0ZiqP1u47ckfZ8dVfVwhERtBWu3WKxORE/q1ns3CgwTLYqbxUFnzH2rTDK9MN
            ljUPBYMQfYytDTzvBQ55q76OWJuuCaTy8XMv80A/r+D83O08yWajtYAJOrK/liJr
            CsatY7nBicY8cnQ563uHxU2LmJ3PAit9t01mU+of2G5wbLw5Q1H2OJc=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIMCY+5CiY48nLEveOMVpLfwBVkc4vWy1eHPZvCA9ucq2oAoGCCqGSM49
            AwEHoUQDQgAEu84acaS8smT6ARj06MA2g3NFLlVcVL3vMu1IA9g7t35M20B73Gs6
            qGe5GsJJyn3mMCBBm2kToP9HPQ7dUEerZw==
            -----END EC PRIVATE KEY-----
