# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "stackrox-cluster"
#   createdAt: 2024-12-03T20:43:11.58097354Z
#   expiresAt: 2025-12-03T20:43:00Z
#   id:        f2c27316-922e-41c1-8233-b0a6131eb093
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZDCCAkygAwIBAgIIOSEFWCVcdvowDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI0MTIwMzE5NDMw
            MFoXDTI1MTIwMzIwNDMwMFowgbsxLTArBgNVBAoTJGYyYzI3MzE2LTkyMmUtNDFj
            MS04MjMzLWIwYTYxMzFlYjA5MzEiMCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xf
            U0VSVklDRTFIMEYGA1UEAww/QURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAw
            MDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMRwwGgYDVQQFExM0MTE2
            NTc3NDEwNTM1NDIxNjkwMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZAxJsQo5
            IRSm9xe5Njr4Fo0VFk0LidlKmMJWLwe3Ri6drFezDblEKYhwv+W7reokPI2Ky9pc
            t1dmYCQoiRDkvKOBxzCBxDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
            BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFDFBnIqD0xNV
            U9jWzUij9zyz8+gkMB8GA1UdIwQYMBaAFL4hl/mJJANISbeUiRfRodjShZRnMEUG
            A1UdEQQ+MDyCGmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94gh5hZG1pc3Npb24t
            Y29udHJvbC5zdGFja3JveC5zdmMwDQYJKoZIhvcNAQELBQADggEBADQtsBJ7XGLY
            STCmIDukOQIdVOKN1O5G+Dmmz82G/SUWXDdGLSTkE2+EKhEh1sBhIJyf4/ZvWuhi
            E4jAl68yRzKpoBBKyMXIDK4FDavMLpwgnAuRzIP61jd18RsJAusSCwcz9nA1Py2V
            cDJ7g2pWWljUKi7f6actLnpDLHKIa/V44DbgxXHG40Fs5ulsg7cSMgz+8nLazB+o
            d2i+Nz5sWsrYrKkGONWot7zvqfMSoXkCvptfnQkq249n5OzxP3FM1aqrG54GRL5M
            +iYtw7jvCy+fzu957OrCN5Ocozt2E1yx2+y0Q74rNHv9/pJn8MBNVE6q2Xo/v3Qd
            xGXzHI8slYc=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIFItoau5Xwa+MuYCDlmU3qWlWC7B3F+qrAq/xJpptQ8EoAoGCCqGSM49
            AwEHoUQDQgAEZAxJsQo5IRSm9xe5Njr4Fo0VFk0LidlKmMJWLwe3Ri6drFezDblE
            KYhwv+W7reokPI2Ky9pct1dmYCQoiRDkvA==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRAOOX+apqlaByQX0swlOT2/cwDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI0
        MTEyNjE0MjEzNVoXDTI5MTEyNTE0MjEzNVowKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEAr8FEE18uUE9lnJ9/9stZF4gRW7BvXT/tDpawEBfet425kCOWUr1drGvA
        +q4cVpCKBVmw0Rb0+v+324zqIyJiS/m55yQ8V5uaV6sqRw/acXdicJWa8LCfj6++
        diujQpTgW/QqTaf3JljDYIAJEOc+Mxpz27TaIFxk8rPkG722gZrcGZ4pE6Ts3L1w
        jU+h3C7cg3tyyBal1KnKvU70647x3Dga/BkUfVrLk2GBPy1QMLtOuL6V2s1uKzB1
        szZo69wJ5RKAS0PyjLOMr+vXdb/0vXeXH8smeqqeEgZQr3wov1oHBXpkr0Coz6nX
        EHj8yRFC9ml0xg6cPPVrlZDAG9SPbQIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFL4hl/mJJANISbeUiRfRodjShZRnMA0GCSqGSIb3DQEBCwUAA4IB
        AQAXtMKN/RZwyU4TKu07YAeqY81ag0dMGlCeiOX7+eGF49r0V9N1EYm2wBX7sM/x
        sf9Gk0cSa6noEcbHBKLBD51CSjA3aB+1Qfs/+VmiBOUlF6B8Nyu8iJZI8f7qxtIm
        SwD6iE6CLjgLhsSnElfyjeOQcWJzPJ9uxRBMc1HnrxXO1q7pM1HwzgPUAn/gAZk9
        WoMxiqhB/FH2qoX0SKhWIC+HBIQIYmVa+ceMhyf5+M6M901OpO3NbwvcDLY304ZJ
        twm3KUkKIwq7tB41tdl3KQbtYEM90vG+/AwxvEMeeGhM2Dl8poyBuGv2gMNtYzZN
        O5QOA+DYMNf7eMtjvDKVT/mY
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIIW1lRkRHzI9wwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI0MTIwMzE5NDMw
            MFoXDTI1MTIwMzIwNDMwMFowgasxLTArBgNVBAoTJGYyYzI3MzE2LTkyMmUtNDFj
            MS04MjMzLWIwYTYxMzFlYjA5MzEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzY1ODIzODIwMTM4OTE5NDU0MzYw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARiUDGePx7lAkUJcNUHm9VaJsAMvKR/
            j2jvABh8mq1ZfS6unIo29ce26jER2Q3ledH4zX+tB0FNQZCQzrcrrrBso4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU2z7+gzAlCFNHWVxTER34MVhzvPQwHwYD
            VR0jBBgwFoAUviGX+YkkA0hJt5SJF9Gh2NKFlGcwNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQBzEdGLVAYsY2wRiexAwo5QjX0+KtCnXRRfTLaIIKsBY+teCjlFxO6s
            o6aC50iQ6Gu2UJz/32J13CgyJaNMuXEPj/PErS07E2M4tI7FHA9cFbuDSQUH6Hod
            lbQtTK2fIvWSxZaQz9vYkHGBf8kQK+3bnkRde7ihu7RtgAm3HJmDerBVwRvn7Wzl
            LTJ5F/EOTuYxf65X4bfEL3lQJb11KEqdZGo0Zemd8LtlX8DQzsldtCp1++PxVhlY
            Wq5b/dGD/4v8oM4bc7CF4HCZL6c6n2OV13MbqUMn/jNwxVkgbP8tkp/EQQ/E5cOM
            LQed8v4gg/YxbQ1u5L97O4KLF+JvMo84
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIDAxZg34Uj+HEZqOQwJXRdLEExCuxu9VsIXcQyaNHHlhoAoGCCqGSM49
            AwEHoUQDQgAEYlAxnj8e5QJFCXDVB5vVWibADLykf49o7wAYfJqtWX0urpyKNvXH
            tuoxEdkN5XnR+M1/rQdBTUGQkM63K66wbA==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVzCCAj+gAwIBAgIJAKz5GEQ2/sB+MA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNDEyMDMxOTQz
            MDBaFw0yNTEyMDMyMDQzMDBaMIGmMS0wKwYDVQQKEyRmMmMyNzMxNi05MjJlLTQx
            YzEtODIzMy1iMGE2MTMxZWIwOTMxFzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0w
            OwYDVQQDDDRTRU5TT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
            MDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxMjQ2NDAyMDEyNDk4NDA2NjE3NDBZMBMG
            ByqGSM49AgEGCCqGSM49AwEHA0IABH+1v37/Ye1sD5MjLZ1fFDGG+uzq4zalG3OC
            QLGOuyEQvaZ2QctNb8m5y5f2/qllVpDSXCjFULT1GlB111rGtJ+jgc4wgcswDgYD
            VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
            HRMBAf8EAjAAMB0GA1UdDgQWBBR3LSywrZmNpiPWyJ3GeG4Mitk/tjAfBgNVHSME
            GDAWgBS+IZf5iSQDSEm3lIkX0aHY0oWUZzBMBgNVHREERTBDgg9zZW5zb3Iuc3Rh
            Y2tyb3iCE3NlbnNvci5zdGFja3JveC5zdmOCG3NlbnNvci13ZWJob29rLnN0YWNr
            cm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAIIiu4MNdPw7Y/rbu6qu/B51rjjOW
            4sTuKq1ZyOuktqpXAruffFuKN303pqLzI7WP8BB7ts2tXOBlnjOaBuC92NMR1ZNE
            QspddnCjIgRH3QmjxGTibqiFhoTtx7jcm5in91wDmCeLz4Vaplca0e77jsZOUkgN
            lkgKokJEI5X5jQXWNxuO3yoUtEnpWMQbqf3uMDRU3iRFcjYaUg4MO7oTNY7JLet8
            4ah1PC6PJd/pxT+jfjiidfpjcrKJZCL1m+83lAJXzwH0PoPbzrsyu4daK5Q2o7j8
            T65+zYfs22ghIXTnYDRNlIgqrwq9ugUQhmHTt9mropQ3ugFqXrgxUTlDLw==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIPRHmrKnOPNg3pLkla0vTpQTvcuYK9s8r9CH1j37PbdooAoGCCqGSM49
            AwEHoUQDQgAEf7W/fv9h7WwPkyMtnV8UMYb67OrjNqUbc4JAsY67IRC9pnZBy01v
            ybnLl/b+qWVWkNJcKMVQtPUaUHXXWsa0nw==
            -----END EC PRIVATE KEY-----
