# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1766146993  nanos:534574457
#   expiresAt: seconds:1797682980
#   id:        b2032c73-cc48-4d1e-9cf1-7babc8ce2920
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZDCCAkygAwIBAgIIVN6EQNP0bF0wDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MTIxOTExMjMw
            MFoXDTI2MTIxOTEyMjMwMFowgbsxLTArBgNVBAoTJGIyMDMyYzczLWNjNDgtNGQx
            ZS05Y2YxLTdiYWJjOGNlMjkyMDEiMCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xf
            U0VSVklDRTFIMEYGA1UEAww/QURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAw
            MDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMRwwGgYDVQQFExM2MTE1
            NDcwNzU3OTg0NDk2NzMzMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEebaT89do
            OTdxCDsptQqzel7nLd5BejJiwHXnCXeoeHdjxWY2rLI+Nkio5CmbH3VZfrpq2bbw
            /cvfVZpEGWv9/6OBxzCBxDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
            BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFG+txGUpW5Xi
            sz3Gn8PeUQsz8D73MB8GA1UdIwQYMBaAFPtRNvC4jjpt1uYfsfLxCI3AS6yQMEUG
            A1UdEQQ+MDyCGmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94gh5hZG1pc3Npb24t
            Y29udHJvbC5zdGFja3JveC5zdmMwDQYJKoZIhvcNAQELBQADggEBAMeYSQIjmQ2Z
            HYUkTlfsFF0wN2jsecoLziXz7slUPCegwyrnEsdSXZz4G7Mj12t4MDetk42+CIJW
            vrmjwZebC/ZNjn46w75b8VMddBT77SzI8040BZKAQexyDzEw8B9FC1O1GqQ4QLFD
            p/XkvPNI0EuKeGir+QoaB0dhQMSS+6LUfFmo9g/cSWtOqGLWPd27EDbZlQqFizwI
            jjk5DvqTchZabeNHUrLdemkoW8ln6E83733pJr5j4vTlWVIwta5SdkR1M0z/0L1W
            sQnaRBruSP+A8CTday+Sj032H0cz2/vh1JQ2vqkRK9cZPB037UaGBJb+wqfh/s8q
            caEQ4x+yNEg=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIOeGYCNHY3TzaAI8BkO7yrlBSZ8yjWBFUzbpbtYrjUbeoAoGCCqGSM49
            AwEHoUQDQgAEebaT89doOTdxCDsptQqzel7nLd5BejJiwHXnCXeoeHdjxWY2rLI+
            Nkio5CmbH3VZfrpq2bbw/cvfVZpEGWv9/w==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRAOHkzYTeGmmEAB+FYkP/bCMwDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1
        MTIxOTEyMjAyNFoXDTMwMTIxODEyMjAyNFowKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEA0uFJm6ZEZ/7WaHfMixz+eIAryNAVVTKWxC+W//Q/1XF5hIz8ZYp8wZwv
        JhBXjwB9iZiF4EmKNK86HtgdjDkqwJiqMCaN5EyULCiIqvCHkicTz45GeEVQYE+2
        Qz70shAInkN2T7DNqMI+WNMNRpmQnqa6t0zvqspoWHbbdaJD9/RQYtWPv2msF+xv
        VlSpr9IEhuboxXe6/5a9bDmtMXTwob5A1mp6GGaWocVBhyAVGx3/5H53jgioTy8A
        hXC4cR5CUHBcTrtXHxNHj/IiUbRSvLCueutKd424Vh+O9RloJV5amjklHf5Ile79
        HmG3TkNRJ7yHM1aNlwrzABc1HzE/QQIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFPtRNvC4jjpt1uYfsfLxCI3AS6yQMA0GCSqGSIb3DQEBCwUAA4IB
        AQARdrYaozi9ZgPJaPbDQ9gbOoYROVlSf1gfTCz7fDGuCegHkUnL/0Ol5dcntOEK
        NU6MD3MMxET0lntnZhnFPimDBp4CgF69s44J0GL9M5IuN2eeZ8qiqgDn3HWYV//n
        OkEdMz183UyjtnGTnpgF9KXi10/EHq5rLvcGppMLNj3EJ/ZCHx3FXhsohhSFDg5R
        p7KOHwjG48cjfjufVtgoSq8kPfp8G84Pn39c070i1/xyRYl6a93ti2Izqcq2wsbK
        1nI8rnbVNRedHGksLGty2DzE2Zc52PvfMMX4r1xt0MAxJfSqR8zbypHQ4E8yTJOi
        YRPGBR5WwcGVBGTgn3qSqWcJ
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIIIWxFV0JWZmEwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MTIxOTExMjMw
            MFoXDTI2MTIxOTEyMjMwMFowgasxLTArBgNVBAoTJGIyMDMyYzczLWNjNDgtNGQx
            ZS05Y2YxLTdiYWJjOGNlMjkyMDEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzI0MDgzNzYxNDE4MTM4MDI1OTMw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATPuPQKKYt9WEXvDd7/7fOs/5/AB5fj
            1rgoc4IczqKzwcT9ob1Hr4cGE1536Yyns7sKKIy/1wOyi07n2UIpZpsno4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUsngkZ2L73Six9MBIl/JykcUG7UMwHwYD
            VR0jBBgwFoAU+1E28LiOOm3W5h+x8vEIjcBLrJAwNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQBoG1U+Rr9lSe2dWTeNgARXCA2G9z4W2wUatkz46mZfpz+LLaWxg5du
            EVL4oyvsx0zGdOhytQnxh8MkrTLNA7fZgbBxmer4xVfoc0jki0XP4SmODjCRAOZp
            5Ggcy6QeTKh7PDRxd2cR0Wg4lgEmpMpRmZYLG2tzSY7Q3SToUgta+p1CLut0ci0r
            d24bl6w0nOWuq7pJRtYhuKUWpSZ1Ka+yxxHdgS36gZVdCAlU/wKrQiixSTa+Ti/N
            VGbqbEHaFuRKkpb7PorlBPxYqpMlQXeT5WKT8AL9qvNQlPMbGS4uPdHbtv2ZxGgW
            JBCjup93D+023v8+bV+BS6sYTGG3WwLC
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEINPZTcO+TBG1sFT9ZYrjQMhf8RsOeeH3p21dIYll7PumoAoGCCqGSM49
            AwEHoUQDQgAEz7j0CimLfVhF7w3e/+3zrP+fwAeX49a4KHOCHM6is8HE/aG9R6+H
            BhNed+mMp7O7CiiMv9cDsotO59lCKWabJw==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVTCCAj2gAwIBAgIIU8NaImP7zuEwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MTIxOTExMjMw
            MFoXDTI2MTIxOTEyMjMwMFowgaUxLTArBgNVBAoTJGIyMDMyYzczLWNjNDgtNGQx
            ZS05Y2YxLTdiYWJjOGNlMjkyMDEXMBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7
            BgNVBAMMNFNFTlNPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0w
            MDAwMDAwMDAwMDAxHDAaBgNVBAUTEzYwMzU3NjcwMjkzNTk0MzEzOTMwWTATBgcq
            hkjOPQIBBggqhkjOPQMBBwNCAAQ6uEnPue7xaCvB/vbKqMTo3803ZBDGfdzyTbA0
            FHnvnoWsR2tahz4m86BIrSiuJljYta7x93GIFxx0x5zAGSm9o4HOMIHLMA4GA1Ud
            DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
            AQH/BAIwADAdBgNVHQ4EFgQUQ/yH1TvB0M9GA2ixOhaktBG6FEUwHwYDVR0jBBgw
            FoAU+1E28LiOOm3W5h+x8vEIjcBLrJAwTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNr
            cm94ghNzZW5zb3Iuc3RhY2tyb3guc3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3Jv
            eC5zdmMwDQYJKoZIhvcNAQELBQADggEBAAkJkhdf9zPiO/qxSsBLG+gmh2+1EO8M
            5zA3D0fAuNuhOaWd7rnivdtsjrxaMFaVzTqbplmfDAqLEcAWdeBxvkhisd/c3YCh
            dlsqM1ZTjvDhKlzd08u4G9BAkgqCE7oAqCDflhTxSXGZtHyVOg9KQfwd7avXBTsf
            7kZmSfnjrTUZGGnJN99JYKDlEoDy3A4bFGOL6hefr3Iszb8uG2U6LXG3vs5D1O2z
            cdTM86ezMA9dD5eTuDvXbABFd2tColGRUbM4bXhWmGCByL/KM7x5h0SkhazpJIW8
            Y39walkmScUfb2Gy7EipBLgxRBNo6wm9ePaBD8eQTcrH+GrU+yPZSeE=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIOlmsd9qUm8LIMu8ZTj4Yyfn8CvM1Q8QLDYIC24Pc/U6oAoGCCqGSM49
            AwEHoUQDQgAEOrhJz7nu8Wgrwf72yqjE6N/NN2QQxn3c8k2wNBR5756FrEdrWoc+
            JvOgSK0oriZY2LWu8fdxiBccdMecwBkpvQ==
            -----END EC PRIVATE KEY-----
