# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1746834517  nanos:488262925
#   expiresAt: seconds:1778370540
#   id:        54957207-d48e-4c52-9bf3-4eaf062e5688
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZjCCAk6gAwIBAgIJAL311AYqMKavMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA1MDkyMjQ5
            MDBaFw0yNjA1MDkyMzQ5MDBaMIG8MS0wKwYDVQQKEyQ1NDk1NzIwNy1kNDhlLTRj
            NTItOWJmMy00ZWFmMDYyZTU2ODgxIjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9M
            X1NFUlZJQ0UxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAw
            MDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTM2
            ODgwNzk3NjU0MDUyMTQzODMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQoxavT
            tMf1bcWJvKxulKkNVeUApjqcnzI0a8X3mlM40EMRBIrt6zVGo7emvVSq38p+PFfw
            bC4d5fLDfwvIajq7o4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
            BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUGQ3VrL09
            STaLGbMwSVhKURAMAS8wHwYDVR0jBBgwFoAUJdBhitaiyb2RcGqy/eZlXtIMWj4w
            RQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lv
            bi1jb250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAIVFsviEk
            KNeVZ01q0U22AEYuZhAgjhT0inHQkNvJI4v36KlF7YWV/e8rZrf1SkArkVrz1HYu
            C60QiW8mkxNLAbB/aoRy+aCUQImGNzCuSF+8pXFhilxBG9BAK2WZCYEIQVyYjAu1
            J77FKa0q80p/gcFP7Em4zuvel8H1J+RT2fC5OjGBj2u7xv1dl1G/GkcrsDSpqBLJ
            S+UYK+vYWKnpbCVk7nmg/AfE1fn25N9vjL7LWOe9qg5sc/IbV09qP1hq6opUGisL
            iMU5If/Mq7RC6IFsJLY2O2mwpcqzXso9KJWI4oLwl+ca2feFfeK+qL6TLJj2HQgz
            NjEfBFzL5jEjrw==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEILMRxmsRwBBYDRZPoB68B3HZN4O2zuNulqc2L/Es+iTzoAoGCCqGSM49
            AwEHoUQDQgAEKMWr07TH9W3FibysbpSpDVXlAKY6nJ8yNGvF95pTONBDEQSK7es1
            RqO3pr1Uqt/KfjxX8GwuHeXyw38LyGo6uw==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRAP18NztKlpAjvx1RHcRH7wQwDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1
        MDUwOTIzNDcxMloXDTMwMDUwODIzNDcxMlowKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEA9+LNKjUyxSIZcV9L207cHEOZ3k3QiaWC3HBBNz1idqMPbPxClU4iKqE2
        r2sJha928myFAOxp6XM1R/nXE0pi1WW1StVCd2wYv/EQAFUpNmFjMTTRNZVgyfCy
        TxythGlceJQ1fRxvuNyyoWVWSVZp6nSAz/FfR/7PU+Yb7NI/zugPHHEohTIJKUKH
        Xg2/YrSp7CJw2VKJOm7nTCjRwvT/0frujHEywhlwmXjEAAGKamXzAGJ70KB19QSv
        08rz/Wm1MPb3vRKh2OywrNEnvXO25hZ8gA7JH4sQBr4RGs1CM6es5NxQ9wX9LHbr
        ZhMB0DwMYaEOiKwinNytdjjNHmWqHQIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFCXQYYrWosm9kXBqsv3mZV7SDFo+MA0GCSqGSIb3DQEBCwUAA4IB
        AQCboqB6NGM/G7fLgPzdZ8SwCL1zFiMvIql5NuIrFdQTo2uMMuQHp/wfLYwQZzKq
        WP8ox41MpYgM4fpfty5VfMZhSsCCAbeOKwEGv9ODSusaGlKGQJaRZqX4XC/gWETb
        B8R8kRpsHhZBBX7bNDAqa5xlazNvVwYaBzubSP4LH0p+TSJdW3moODPXuRaZTHHb
        crpMxGzg7NS9mRxfBP+x6+JmRm0GxeykBu6ZKD0I5LncWCQPwcem41PnD4wl+Uxf
        79+S0NdMPGpbdFJzJG4Av2fv44kvhby7IDgd2FoCZDQivPcY2ST2KXNUuS5UQCKN
        Gxdf+znHGFxL9mr67zQL1nUN
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRjCCAi6gAwIBAgIJALGE4GjuZFRpMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA1MDkyMjQ5
            MDBaFw0yNjA1MDkyMzQ5MDBaMIGsMS0wKwYDVQQKEyQ1NDk1NzIwNy1kNDhlLTRj
            NTItOWJmMy00ZWFmMDYyZTU2ODgxGjAYBgNVBAsMEUNPTExFQ1RPUl9TRVJWSUNF
            MUAwPgYDVQQDDDdDT0xMRUNUT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAw
            LTAwMDAtMDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxMjc5MTU5NTU4MjkxOTgyNDQ4
            OTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABF4bbh08ZQQ/veH7xFc+1z41YQMW
            f87fa1Vz9/vTp1E9qbhJMpJ9F6T3/zX0+156Fw0EY0HwCPREiwYVOzYdqlyjgbcw
            gbQwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
            AjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQE3wQStalOPKGblvMrMn2qlz+sIDAf
            BgNVHSMEGDAWgBQl0GGK1qLJvZFwarL95mVe0gxaPjA1BgNVHREELjAsghJjb2xs
            ZWN0b3Iuc3RhY2tyb3iCFmNvbGxlY3Rvci5zdGFja3JveC5zdmMwDQYJKoZIhvcN
            AQELBQADggEBADEjH7RJrF4g9CnOhCJKmvoHOQqrNEJZOWjQ3yEYuH56R2jocNZ3
            jEbAQEIwEeaPIFjm8VxceHpPB3sL9RFtmQBKowHkg1JslhPCC9teS1L/NhVZLRje
            1vYi0SOCBEnsl+0WgzwAtrulT5J9r+uefkiXyehITe5Ed/zdPV/5jdQOtI8XebWc
            Ztvoirs2EqG2lHSiKIpMr9mLBGA33IM5pdSfXauIyK9GcdvBwJj1wzVgLFMpWgiG
            nL0QUCAb707AGouZ3JEFbVUwTMaKsfEnhHVpnFFXCnIgY/tO0yU4FQb1S2rHQ6Hw
            Kibb5/4Dg4o7aK5zGY6ORBtMbRXhjsEgoRA=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIDHxv4vHtlg25Knns7clZJ0+6d+JA+5+P3bEQ8pZ4stdoAoGCCqGSM49
            AwEHoUQDQgAEXhtuHTxlBD+94fvEVz7XPjVhAxZ/zt9rVXP3+9OnUT2puEkykn0X
            pPf/NfT7XnoXDQRjQfAI9ESLBhU7Nh2qXA==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVTCCAj2gAwIBAgIIHAmxKvIgUlEwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDUwOTIyNDkw
            MFoXDTI2MDUwOTIzNDkwMFowgaUxLTArBgNVBAoTJDU0OTU3MjA3LWQ0OGUtNGM1
            Mi05YmYzLTRlYWYwNjJlNTY4ODEXMBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7
            BgNVBAMMNFNFTlNPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0w
            MDAwMDAwMDAwMDAxHDAaBgNVBAUTEzIwMjAzNDA3MDU4NjEzMjUzOTMwWTATBgcq
            hkjOPQIBBggqhkjOPQMBBwNCAARTFMIwQFeTdUc4Fr+YAC3y1c32L0AoNbnPO+Rs
            z9iAREah24V8ZBdHx78PeaT1LZ6WadhEl3JbPZU9BHRoiGSPo4HOMIHLMA4GA1Ud
            DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
            AQH/BAIwADAdBgNVHQ4EFgQUD3l0NIcYEe0FGE9HiPEikpHlSTAwHwYDVR0jBBgw
            FoAUJdBhitaiyb2RcGqy/eZlXtIMWj4wTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNr
            cm94ghNzZW5zb3Iuc3RhY2tyb3guc3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3Jv
            eC5zdmMwDQYJKoZIhvcNAQELBQADggEBADLM6wM+Cg4FBTT5nLw6q42n1pb56wOm
            mAZ7WRkcSL+5SUqkP6nbcoIc/SC/22sJIZOh5EIeotDCDNg0IFFLoBhMrvnILAjT
            yIyIZivkQ2L5CIvJYx+1c2H8YUsPdQu+CF+KkP7UampXe155DvzjdrdPA6xzxbS6
            K5V8giLNfvnDbPdU+zqEuUiSiQArDnFQEvdlXhUJNZPpf1qoy2B4sDobaK7Vw8Ed
            9Lyk6zxjjbwqX9FokWPbLjI4JHvhyYOsSa9kzOvNJ+RAGTsi4Hus9xlTyA5acA4f
            +6OEdbkgjZkcTlf+1QC+M9Hq0re2fMeINFp8N/ByGHrkMzDV7TrNGu8=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIGylwLH1cMZr5eQeNAvqIcdkj3iDxX4atb4hDD3ks5UVoAoGCCqGSM49
            AwEHoUQDQgAEUxTCMEBXk3VHOBa/mAAt8tXN9i9AKDW5zzvkbM/YgERGoduFfGQX
            R8e/D3mk9S2elmnYRJdyWz2VPQR0aIhkjw==
            -----END EC PRIVATE KEY-----
