# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1746821194  nanos:564919670
#   expiresAt: seconds:1778357220
#   id:        85f78f49-6a41-4255-8279-b8e16e024153
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZjCCAk6gAwIBAgIJAMG3KMAlHfpAMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA1MDkxOTA3
            MDBaFw0yNjA1MDkyMDA3MDBaMIG8MS0wKwYDVQQKEyQ4NWY3OGY0OS02YTQxLTQy
            NTUtODI3OS1iOGUxNmUwMjQxNTMxIjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9M
            X1NFUlZJQ0UxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAw
            MDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTM5
            NTg2NzAzNzU3Nzk2OTUxNjgwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASHH863
            RO4W/0P95dmQgcTo5vQZSeZAJdd+6pDChBIleWOZAxr0ZTkGzpoXpbYCcHhrXRB0
            yf0NigP/tSeL/pYko4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
            BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU7FF8qW/b
            pqdPDWDJnebQtA+k72MwHwYDVR0jBBgwFoAUneci6YjsY1s0rNpPAQXxAokLTIIw
            RQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lv
            bi1jb250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAweiHr/+q
            eQFjVK3agmbirqmZuKWhG4sV/k0pU2P3GvXSwhgydJlNczrG6CiFhy+QPbrj6hoU
            aBjA30hlIC7D6g0meF/sC6+Dtr5Nt0NzmqxmYaldsF/6VQAS7Z7lPKUFzeY5l1N7
            v71wd6DrP5YDBEGeRcu1YRAbise7Li7OxmDB0EvXXbh4SIglpfHIL7lZtM345z3h
            At+TwIZVcanfcz437tFNsbbCvOgphsdgMYR4/auBcwgQp1dQa4RPMkx36zV0mFpB
            B6Z4jYEhRr4kcdVVE/LW3PkqRFPHcm99C4Kg2bqVqiD/iUwNvVU0/KHMj/RVc7fn
            bFWUrTasSR7R0w==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIBfKaU7C97fPhaWJ8NOtpBc9miQgJZIWEvrH3KDpTr3KoAoGCCqGSM49
            AwEHoUQDQgAEhx/Ot0TuFv9D/eXZkIHE6Ob0GUnmQCXXfuqQwoQSJXljmQMa9GU5
            Bs6aF6W2AnB4a10QdMn9DYoD/7Uni/6WJA==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRALAOajvAX5U/XznXRYsGaf0wDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1
        MDUwOTE5Mzk1N1oXDTMwMDUwODE5Mzk1N1owKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEA1DDEDI+aMYfZ7M0qYvPN4FjXW3Gxy0bVwoWL63+VTqD3t7uf1u0wRQ1u
        qi276LMhdguhKW5dQ/geUdqxmDC8qe6Fre7OteYmAc7P3ujeYzcSbE1wqGA3wg4c
        hNW+ThjKF5Q++Xzo1eQ2ssN00YrS05TxnNNU6eRDsZZi3NI6MI8ER2pjZ6uKcu58
        v80vmIrTEwQTdBwG+lW/POGWpJe05RW71UA3kvZxFV16RdRvLUD0TtmkLadaQn4X
        udtWtF1il1Q5xxkdWA7FxvMi+akqfys7xGTnFlWMksdOgXyF1fiH1TJo/cF3iJWh
        lOdw3GgIrvprr+vah4sl8p+bFO8POQIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFJ3nIumI7GNbNKzaTwEF8QKJC0yCMA0GCSqGSIb3DQEBCwUAA4IB
        AQCEPGv/l7Yq9a9DKuMUHu8qAGIPhQYRVZ23MJuMeClgOixlFyjP+9LWGVRakDEP
        kjhDCGSZ8lqgEhF9DGFZ794Rn7hWcq3XuwiaQXacy1WXJYR2IhmcQO+1jKSXMf4P
        2uqSlQ/57ltgdAsE+VNCnDNSokP8e1TWBD8iuwJFw0Xh3R+FP9DciacheBppE+5Q
        D1I0aD6uYINNzPV3DLWiVPLGxCABLR+jOCJDv8ccZ06r9zHRR86SqLJMSGzxAbSr
        o9cD1fvV4UkO875xK0giV0g1696KxpNWfFGDOYrs7GrARH6Zt4B2HGMn7nDm8zAZ
        ssm3cdzzro4umRryLngJUz07
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIILaFbcbYIANUwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDUwOTE5MDcw
            MFoXDTI2MDUwOTIwMDcwMFowgasxLTArBgNVBAoTJDg1Zjc4ZjQ5LTZhNDEtNDI1
            NS04Mjc5LWI4ZTE2ZTAyNDE1MzEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzMyODgwMDk3NDY5MDA1ODI2MTMw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQH9tk59vcZTVuyLC1LLvshKV/64Dgb
            4kJx69uYPAXsi3wSx5F5mNGTuKjGR+/3woUs0f+OA+U1JFUJkcKg0E9co4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUQDt7QrdUR/Xx49PBV6iYyw92ybwwHwYD
            VR0jBBgwFoAUneci6YjsY1s0rNpPAQXxAokLTIIwNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQCC0cmm2zCSH+E5oTuAjtX1l7R5g7BtOVMJDQrOUZ5h6XnCwQ+2w0am
            L4Z8RHx0m2rk9dXudOA6Xg4WvuouK8FxcppE4x9+MVXP3BRFOvAZLhk0pC9sN18X
            ZiHTaoucX7SUhEKgZgE6Y1zKF9K/Kqusmqii94OeHNsZm+xwV23zXDZpREwBOcgF
            lhEs2KA11H0e+BpMa1LIzSVm3rm+HQWOmAIwPyGRwwIABTTg94eieC6az5akrVFF
            ir2KDpUX/YcqrjCl+TodYZWMLDc/+lADjcBWArxpFxIeO6z6YTuXjgHWpiw+RTHE
            NBfIE6pRBJIPDxEOfY2g4auOJBfZs4Tz
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIGcb/hH0pBF24oujk3HISYPZGFO5wYs/Ck0E+XoMPI9MoAoGCCqGSM49
            AwEHoUQDQgAEB/bZOfb3GU1bsiwtSy77ISlf+uA4G+JCcevbmDwF7It8EseReZjR
            k7ioxkfv98KFLNH/jgPlNSRVCZHCoNBPXA==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVzCCAj+gAwIBAgIJAN7BUJi9gfOKMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA1MDkxOTA3
            MDBaFw0yNjA1MDkyMDA3MDBaMIGmMS0wKwYDVQQKEyQ4NWY3OGY0OS02YTQxLTQy
            NTUtODI3OS1iOGUxNmUwMjQxNTMxFzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0w
            OwYDVQQDDDRTRU5TT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
            MDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxNjA1MTE5OTE2Mzg2OTgxOTc4NjBZMBMG
            ByqGSM49AgEGCCqGSM49AwEHA0IABKIIV9GT04JaWz9Fnyx5xhDURELQa9zobogY
            QYqoSNdg5kbHCOgLOH3cIcQ2La3/RmpVee6rNOXmwBzXXdy3+2ejgc4wgcswDgYD
            VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
            HRMBAf8EAjAAMB0GA1UdDgQWBBQXLG1f3OvbMqDkurkZXAWgMZI8BzAfBgNVHSME
            GDAWgBSd5yLpiOxjWzSs2k8BBfECiQtMgjBMBgNVHREERTBDgg9zZW5zb3Iuc3Rh
            Y2tyb3iCE3NlbnNvci5zdGFja3JveC5zdmOCG3NlbnNvci13ZWJob29rLnN0YWNr
            cm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEATUFX0eBFDFg5mORk5hIg8SzfiA5M
            Wbaqy4TtSAbDjFRGHQKCOKDH8mlwCcmnzkuKr5HoJ+cizrMtNggNN0NtD9mzDLyu
            BffpFYMpo3pvrsgX/Thh8UZJpx5bN5LXJBaPkCLzOAWvt+qBViBae+UgS9VTiBni
            BxYLhaTGHkktqfmvAz0Ld3dOE3W8mc+YtrDSx19PzxhhNxxl35juYOMFzeZo/XjP
            iAxmKryOdeSSgEEYRncdl6fkph+x4fVbzMPfGg/I2XBdKz9y16tUHI27PpbR5oaH
            jJq4z0O4vd+WXZQWhhBUDqaWAmA4jlo1zQEdWq/lpBi0mb2zKIcj86lBgg==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEILRfoojOperTOFS+CyzFEXo/pZ1qA3fW/X7xqpi09QBQoAoGCCqGSM49
            AwEHoUQDQgAEoghX0ZPTglpbP0WfLHnGENREQtBr3OhuiBhBiqhI12DmRscI6As4
            fdwhxDYtrf9GalV57qs05ebAHNdd3Lf7Zw==
            -----END EC PRIVATE KEY-----
