# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1754517938 nanos:811124176
#   expiresAt: seconds:1786053960
#   id:        a7ae80f6-334e-448f-8fd7-790d88dc4186
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZjCCAk6gAwIBAgIJAMY5XTIcqAy/MA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA4MDYyMTA2
            MDBaFw0yNjA4MDYyMjA2MDBaMIG8MS0wKwYDVQQKEyRhN2FlODBmNi0zMzRlLTQ0
            OGYtOGZkNy03OTBkODhkYzQxODYxIjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9M
            X1NFUlZJQ0UxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAw
            MDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTQy
            ODM1NTAxNjI5OTI3NjIwNDcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASGBv6D
            zDnh8nEOswN/xSM7OCVZ4uW2ZMqK6ckR0PnLSEn6d4C9+olIfXMr45lJZhAvPGyr
            LnQ1Sal0zvVXrSBno4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
            BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUq6hopY5R
            Wr3H4Kjs8XMkIZAwmycwHwYDVR0jBBgwFoAUjKUibTj2H2pvQxRXlwDenNhwYCEw
            RQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lv
            bi1jb250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEANtTcjpkT
            29wos/NO+RQes/fgWJS0sOyJ5cEoTAcQVBQzwCue3nvtXMacwX0q3gpfgMi88UGP
            zq8oed1GFM5/wUsxi8UAVueY5RMiF75dNEB09F2qxblYNnwmpO2r1JtGYOH3F8YU
            9s56Ng8Z80tpwrR8Iker+EPTXCm7kV7mIRk7hhyHDF2BVu0e8mlJadOObd83kWa4
            fmTUwIRufqCAqtjly4YolarYWNFEEr6Qm/KknwzzNEOgpwoIEdGuW/gGuIXx3kOY
            bb8nUWAxfzvw7oCr2GJSVkMguQIZwrMRU/yisvZ0aOrsHDS0BqHcwPBPNBmoQdvO
            rbvyGDLQ2xHn3Q==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIHK6gEnmqezMEafOeTZrMdczVziAQjwY6/vYmEQD2ncyoAoGCCqGSM49
            AwEHoUQDQgAEhgb+g8w54fJxDrMDf8UjOzglWeLltmTKiunJEdD5y0hJ+neAvfqJ
            SH1zK+OZSWYQLzxsqy50NUmpdM71V60gZw==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRAOGG/xJty3WlerqGjTBVIJswDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1
        MDgwNjIyMDI0OVoXDTMwMDgwNTIyMDI0OVowKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEAwQZyMl4WWfaLE4HVqGzjUHtuw4PZeaiUuUDChXps6xH41pC0Lg5VwSPX
        XuMueIbms/3kSSKlUS/dxLfhoqF/ad0bcRu8UVFQMbUc6UZNNz8NvxuIKk1UcEBQ
        LEUwggghnStB4s3aBzpjNAdewEgV4yMfxIVPdvqhn2eSSWoA00yqxlnWS8BU+n2X
        +73llopcNyuAr78jju50tQyZyjgkYjI6UwnPApOCDkonaqfgNZSC7BMdJDDj4nmX
        yWUtomq2Q4ywBFNzkp/dle6+wCKJU25xmOpt4Bp7keps7XNXrUYs021RXeNFk1SX
        884xO1eCCp58cfoj8f9qldj+49uG3wIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFIylIm049h9qb0MUV5cA3pzYcGAhMA0GCSqGSIb3DQEBCwUAA4IB
        AQBZznUzPgUNPwCW9ydDW99z7mDBGxJxFQLqrxkIPNT/ArH7sAVB7cscwQGWxF8F
        EF8KyTjBwzTLwKePXZgyfXLoHkAMBjDjJg85tIy+dayxLP+1nl/MHs6AfA8SmnbO
        lVt0RgLAaxw0q1Hs0GrLoJ+oAov1GppnEX+uM1lom5Hgdzs4wxUK0cwH+Q/DWane
        4NVgmyWV8wUnm2znf8KrVJ0s71g/V+gO2btgHhgVhADldQtq8iz0qu11rNhS1fDT
        UBeNl6KK/vXWHKK/dV1s5ZDMpk1wykllut/EE6tGCjv2MQI3rkIdW+KgKCmaq5Gl
        x49ACwnT6swpzZEc1iecJv0A
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIITF89nhh+bgIwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDgwNjIxMDYw
            MFoXDTI2MDgwNjIyMDYwMFowgasxLTArBgNVBAoTJGE3YWU4MGY2LTMzNGUtNDQ4
            Zi04ZmQ3LTc5MGQ4OGRjNDE4NjEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzU1MDMxODUwMTg4OTUxMDE0NDIw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASkhGaUItK8kvktn07ayDsqg7Fqhb/F
            SEVLw3gMfymk17XBry5vHSCKpbC4hQzbJX+HZnMN7mABOssV2s7O7z1Yo4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUSpZEy6kvQvAkTRS8ZWjb04Ms8e0wHwYD
            VR0jBBgwFoAUjKUibTj2H2pvQxRXlwDenNhwYCEwNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQB/ZCTSEIu0OugkiDDucQ0Bp2W3kQmMni7rdybMRAtzAxBcxNDYPIgz
            44dQVYVjrPSDt8PngrfrzI4H8Yim9o2ggal7zAwU0gYxRVmOLLAsC/4gh9iwPjD0
            4G0ks37Or1FIF2Q5aVfntIr8tMiOSvOK9y1AH7EQSbm1m3Z0kZC5RXjUVu+SHApi
            maAhNp1/5KxDkX9otJJ0lqCkOMnOCX3D3KNoHq0rgXUmQX//WsY6n44exnOP5ehi
            GyyeJO3dvnltg2KEDYMHy1j1iYd7MfMQHVM47BpfnYXNw1M8h3k82HBCXakh/pSk
            fXHWCFayE0+tUIZSN3KPxn1hQ4ZzDFvC
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIP6PCXNS8HmcUGjQFCUmYb2w1R0YeCyNR7390DDYx4ProAoGCCqGSM49
            AwEHoUQDQgAEpIRmlCLSvJL5LZ9O2sg7KoOxaoW/xUhFS8N4DH8ppNe1wa8ubx0g
            iqWwuIUM2yV/h2ZzDe5gATrLFdrOzu89WA==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVTCCAj2gAwIBAgIIOinl9Zv50fYwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDgwNjIxMDYw
            MFoXDTI2MDgwNjIyMDYwMFowgaUxLTArBgNVBAoTJGE3YWU4MGY2LTMzNGUtNDQ4
            Zi04ZmQ3LTc5MGQ4OGRjNDE4NjEXMBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7
            BgNVBAMMNFNFTlNPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0w
            MDAwMDAwMDAwMDAxHDAaBgNVBAUTEzQxOTExMzM3NzEyOTE1NDYxMDIwWTATBgcq
            hkjOPQIBBggqhkjOPQMBBwNCAAQI6kvRpfcg0b7SAa0sF785gE393OyW08o0A00h
            vpijHM3uS32PN/PUQVxlgDKNdoluNqG91aKQFpXLR6i2vTHBo4HOMIHLMA4GA1Ud
            DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
            AQH/BAIwADAdBgNVHQ4EFgQUu05aYkLL41XAURRO3BmrsA0AhYMwHwYDVR0jBBgw
            FoAUjKUibTj2H2pvQxRXlwDenNhwYCEwTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNr
            cm94ghNzZW5zb3Iuc3RhY2tyb3guc3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3Jv
            eC5zdmMwDQYJKoZIhvcNAQELBQADggEBAEAW63yS6ElYOMMAQoqhdoVh36rVVWNJ
            GbsBC19CEiYSZZ8Wol6xnQCt+6b7B/6IZrH+EUjEM27Rcc4YhyJc0cNtdLpwp5jB
            iOfzWc8X0Ue4rBqHRbqHfhhuShZ+w791J262QBc03H5KHHWYxWYhljXW256I+S3J
            6fNIxMvbz6T1aa8VRj2+r1CxLTluEP91Bew/CfyndhMvj9bO+LIwi9FEEymraTDn
            sAnpbwgS0JpWt7wLgOBqG+SWGLl3RyWLoXP5PyUfuCXiDCNetdzvWNwnahPmp4WL
            LAF3vpEzzPf/IbOD5goGd2Q83ureck4306eqwM45yMQuZpxZSVr+qSw=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIArIAJ20TLFHn726aKGrTC43J669RmMDJRybpejMyeABoAoGCCqGSM49
            AwEHoUQDQgAECOpL0aX3ING+0gGtLBe/OYBN/dzsltPKNANNIb6YoxzN7kt9jzfz
            1EFcZYAyjXaJbjahvdWikBaVy0eotr0xwQ==
            -----END EC PRIVATE KEY-----
