# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1754519492 nanos:628593164
#   expiresAt: seconds:1786055520
#   id:        d6508e5b-b1e5-4351-a5e7-3b48dc64b3cc
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZjCCAk6gAwIBAgIJAK75gBEz9hvXMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA4MDYyMTMy
            MDBaFw0yNjA4MDYyMjMyMDBaMIG8MS0wKwYDVQQKEyRkNjUwOGU1Yi1iMWU1LTQz
            NTEtYTVlNy0zYjQ4ZGM2NGIzY2MxIjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9M
            X1NFUlZJQ0UxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAw
            MDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTI2
            MDgyNDk0NDMxNzQ5ODA1NjcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATLzufU
            c/U/cl9tx0X2RMS3P7nYv0EpCudr5aiuyl7LsK+WC9kQ1GaU1bjPjKKVNRnMvk6a
            sacelW9XHmYI383/o4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
            BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUhth5NqOb
            kgcK4cKlJLEpAU2j6hkwHwYDVR0jBBgwFoAUhhF6oAApeSR1sHnnfDpIRHjTL2Mw
            RQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lv
            bi1jb250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAK4iMQlVA
            wGcw87HQYwGolTECb2iZeu19A6Yo9/eUw0uucJJXsUzahABzRBnY/dcwrGOc1Qwx
            g/Vf1TKvGxMRmO90z78ZsIk+Gl1YZ0Wot+mvELOVsqRJBjkRASyMoMS3tGnioKNA
            7OwVefXKn9Tjb8b2s3XFOQm2LzR17W9Oty3dSaoSOrUwnbrMS8TIYg5VVg7BKaCz
            0HwfM6DBrRV2HgoFC0X3pt1PzUaQEEFncfkss8bQqyylOeR7jgKtGPSqZodPoFL7
            FhomOLBy8UTK0gxr5tbz+UU1LplxmvaRqd1iT2dMSyRj8i5TZxWZ1GdArQQWWER8
            umOJH6XHlVx9Wg==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIMKyWeA8DqJDCJIPj0B0Q/qtHe5r91emAClje/rgtXQcoAoGCCqGSM49
            AwEHoUQDQgAEy87n1HP1P3JfbcdF9kTEtz+52L9BKQrna+Worspey7CvlgvZENRm
            lNW4z4yilTUZzL5OmrGnHpVvVx5mCN/N/w==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRAPPsEjAJdFdPeLBR7rMCsFAwDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1
        MDgwNjIyMTM0OVoXDTMwMDgwNTIyMTM0OVowKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEAxu0CcxIhRzSxg2DDzUFOLh5hF90WErRIgyt5VmxXTLtcr3AH/FY3Tuyp
        0iw0RTE7x/VQYgMg3v+hR5OTdhVYDIU6H5Eb1BVSvv+kntNuSRL9mAEDivBpHe+I
        aSe70IyhfCuaKgYaicrCKxzH4be2BRDBZ8s7XHS3rfe2le7NoVO5OoF/Dl+OLr1O
        EPcA9Q18zl61TmCPrS+/5H3e1UU3KeP7Lq/vHPii48jCQaIEhr842wQ/1+T5qy5V
        isnpgdVIHxWI7ptlxHTOnCOQUvHicIp3ac4gBixNnIm/lTcneOIOFiDbGhOmvij8
        HbAfUgpyw51o/6dhjXtKEfAwMA4s8QIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFIYReqAAKXkkdbB553w6SER40y9jMA0GCSqGSIb3DQEBCwUAA4IB
        AQAQyIzZR/Wxg8AMgnq0afSyO11wPgoRg/kbkilvFYvA22y2kkvi2VV7bfksIMTK
        fCEWm3BK7tRHL87AjXX+iV3aRhXa529DuEXLKzC2qai/OEwQIRw6UVHYIAg28kS0
        mfrAEA/incMjj4UINZxVZpk502NMUNLThGHfWao2bpMVnO8xOp2mAbtp8ty0T7Py
        p95YnlDdgJ7ZXSrSMWFjKGKJC107bFWMP4MObQIL6zvYfpvg2r1xMI7aztOcIqJb
        8va3aDJN37FPVvzvcxPJzHdiuCxHDC2a+QXRaQ1lQXNC6XqJWGNiT7vFc4VcJoyx
        3uxljxqc/+1J6Y8NUhwOpoVt
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIIR924E6AucrcwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDgwNjIxMzIw
            MFoXDTI2MDgwNjIyMzIwMFowgasxLTArBgNVBAoTJGQ2NTA4ZTViLWIxZTUtNDM1
            MS1hNWU3LTNiNDhkYzY0YjNjYzEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzUxNzg0OTc1NDA5NzcyMjY0MjMw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATsb64CNK+WzInQ7lVYSOmsBX4sVW9I
            w+hls9dLOTn9JOrmIXAWKj8NXEwJUZjCIbbeY7q7xeJjwQRhR3WaIj4Po4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUYoMbCN0csDbgIl9mOGgXkkTJdtEwHwYD
            VR0jBBgwFoAUhhF6oAApeSR1sHnnfDpIRHjTL2MwNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQBpzKk8TmSt5Lazc16HSQ7T6VvWlEst1ZZ1UyELkI9TCkH+4Sj0J4nM
            0jjnJ75eH/u+uHSQFxRUSf6UKUNhCn97jFqrN/f/uig+PbzwWnKg+3tyJSpUZEVz
            dLdditbW8S3r5SPyhTSGySgrFWcMdnZngH3NKkOd0amWz51hTWZEezyIp6chDtVE
            5R7Um2WlnTd4TfBVIaONg+kg/6kr7uS170ANzUfYOTRpfT24Fz6pzkF1PeZ2aeLw
            zXz3yz3oVtakzC6omPVALh+eoySV+V/wTu/hhst4YHF4HHarg1HC3a4KJkJTaatT
            uxsch3zhIUWrkzXBO2ybW5Z3oBmJJP/2
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIFL/BeKDLDDX+9RfRTEakuH10aJr/m6uxgy42ViO++DQoAoGCCqGSM49
            AwEHoUQDQgAE7G+uAjSvlsyJ0O5VWEjprAV+LFVvSMPoZbPXSzk5/STq5iFwFio/
            DVxMCVGYwiG23mO6u8XiY8EEYUd1miI+Dw==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVzCCAj+gAwIBAgIJANpq1rxXcPEOMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA4MDYyMTMy
            MDBaFw0yNjA4MDYyMjMyMDBaMIGmMS0wKwYDVQQKEyRkNjUwOGU1Yi1iMWU1LTQz
            NTEtYTVlNy0zYjQ4ZGM2NGIzY2MxFzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0w
            OwYDVQQDDDRTRU5TT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
            MDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxNTczODYyNzk1MjIwODgzNDgzMDBZMBMG
            ByqGSM49AgEGCCqGSM49AwEHA0IABI2OPxuvfwMQ4WHHMrLoVQgdb6GbhtT8GP0U
            KMWL6/L37prJSJt/iZNof5Hk4sjGAEVSrWSW8OzqehKhjRm0tjCjgc4wgcswDgYD
            VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
            HRMBAf8EAjAAMB0GA1UdDgQWBBRy8YH9nSOoj9E4kSj5qfatIF3d7TAfBgNVHSME
            GDAWgBSGEXqgACl5JHWweed8OkhEeNMvYzBMBgNVHREERTBDgg9zZW5zb3Iuc3Rh
            Y2tyb3iCE3NlbnNvci5zdGFja3JveC5zdmOCG3NlbnNvci13ZWJob29rLnN0YWNr
            cm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAFmzu4RQPjLPn8EvtP+1TFv1yF0lF
            /SXWehYJTzaN80MzIXOhFdgltGy5Oz+sdUp0vkJBpUjiRgH2cPMpwG9xp7sucB0q
            3eEAyI3Fz012aEm2PuNSzKmL9zKr3yQhUzrOVh3+0EeCwEDqA0DqLBGlN8CSBZ3W
            Dt3FYWT1+qLcwhhxqO2Wc7tS6CpxFvy0PXSZI4Qcdg9CG7goeuFAVGSQJCjAbaHN
            +gXHqBX1bYnc8zNQnIGPqPjuWuJtcyRngdGVi7C7mByDDmoEFpxrqIG3wo9agEXO
            Abz04mU11dOzzhZ7+OLWUgK9R4J+pWwHRiVUGwdapbu3qM9mBzZLHPXb9g==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIFxtT3a0otW+tUTzlyhQsLYk5xiAvJTYPLfYEsC82kwioAoGCCqGSM49
            AwEHoUQDQgAEjY4/G69/AxDhYccysuhVCB1voZuG1PwY/RQoxYvr8vfumslIm3+J
            k2h/keTiyMYARVKtZJbw7Op6EqGNGbS2MA==
            -----END EC PRIVATE KEY-----
