# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1754508449  nanos:558616068
#   expiresAt: seconds:1786044420
#   id:        360c009b-1592-4b22-b621-aeacf07f019e
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZDCCAkygAwIBAgIIZWUz7JWYvp4wDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDgwNjE4Mjcw
            MFoXDTI2MDgwNjE5MjcwMFowgbsxLTArBgNVBAoTJDM2MGMwMDliLTE1OTItNGIy
            Mi1iNjIxLWFlYWNmMDdmMDE5ZTEiMCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xf
            U0VSVklDRTFIMEYGA1UEAww/QURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAw
            MDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMRwwGgYDVQQFExM3MzA2
            MzAzMDYxNjkzNjExNjc4MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8CIYNu6Y
            3a8PkRkHU+mDo2eGNH1gwLd+xyzPIg7nLzwNWcKeLAQsmHw8MwlzUyOHW2ZoW1wu
            LtPg3duI1Nk3k6OBxzCBxDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
            BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFHdTXQzd5cH6
            ooUIPS4+M2IeS8HuMB8GA1UdIwQYMBaAFBjHVBKsrP3CarWaS0iF2w8YFeSVMEUG
            A1UdEQQ+MDyCGmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94gh5hZG1pc3Npb24t
            Y29udHJvbC5zdGFja3JveC5zdmMwDQYJKoZIhvcNAQELBQADggEBAD2XkLOQ2bPR
            FYLLtdc+5UYx6Y5ha41SRQvBJ8IGheU9ZM6yix+lt5dSghCLVwTi7bupRJQhgAwJ
            nlrOJg5vmf/2BPKt4srbo6cMN3NqMpdhbq/g/f9KCjasyPKCgMeAAFoQzsChEoCA
            hWw7IGKwFhBHBvSaeYonqGyWgrVnjO+Rb0WfHZu4nbM8Olhhdah9MfOsQypLoYD7
            1UhK5Ikze6F7/JpiY0vIKHS1LHO598wyw2vnMYwN5XQEpsPfOGiD62dxmEJzbAP/
            cwJVdPjh9Rppl4i1V0v+EjCOxV6MFf+mvvm7+JoB1VetMkvZNjL+faqSunqyq96x
            82LLT12P8SE=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIJde4vEpWn0Lof20tTDGBm+/5zirvX18uUaPYQs2flGnoAoGCCqGSM49
            AwEHoUQDQgAE8CIYNu6Y3a8PkRkHU+mDo2eGNH1gwLd+xyzPIg7nLzwNWcKeLAQs
            mHw8MwlzUyOHW2ZoW1wuLtPg3duI1Nk3kw==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPTCCAiWgAwIBAgIQQdt0WRBBccj+glntDRu4rDANBgkqhkiG9w0BAQsFADAp
        MScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjUw
        ODA2MTkwOTM2WhcNMzAwODA1MTkwOTM2WjApMScwJQYDVQQDEx5TdGFja1JveCBD
        ZXJ0aWZpY2F0ZSBBdXRob3JpdHkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
        AoIBAQDSZFRdwr+3GVqtrB0Wk7OFQEXJNE3jrdPSaoMLy6PAnV0r6X7UeRMywYsd
        4NQq4AB76ghZqbJbSfwU3Mg6pDZJx9yLvgi/AywoNR4J3M7SRf/jMXse0td7J113
        aw88CdqfkGcsDx7tEdoiV/0/bRKvw80Q/Tp2Z/Kf79sns6bXDYooZfVWWKI08Rk9
        /DQ3TEJ3OMZbAnGNANSAF37OKpHvysGiJIxNFIYuHQJmCd4gAQbAgKY1MCsli69t
        d81bapTGnuAY1nIxlZh0xEzUF5mwVUdSgxdAelll6aLTd97JFX/BJ1sX+hVkhD7s
        MjWTw+KyFGeTsZjFKh5TnUx6g5OdAgMBAAGjYTBfMA4GA1UdDwEB/wQEAwICpDAd
        BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAd
        BgNVHQ4EFgQUGMdUEqys/cJqtZpLSIXbDxgV5JUwDQYJKoZIhvcNAQELBQADggEB
        ADYBoqoRUH3E/AwiKSjEODhxhWEFEh3glW74PJBOdPgxVuTjvGHfq3ckBrNH+0Uh
        08LnyMJTQpdCNgh5Ie+10piVATZDk1FIlijeCZ/Jrev1UfH0beobD2IzyW2BgMCD
        bOGtU9ldT39kXtgihjTau7C1sSv0cePX3/Ovf9OolT+m3VUoOOVZm3uuABrxBIvd
        yHy/rnpQIVI4/pfgE/O2bE/YuJM4mX0ud/StPPapybadIBFyCi1K04K3Itpl0Elh
        FY4m19FvZ3BnnaDxa37gVzDeAVnoUf9eKOjJ5cuGKEZULzYg/7bQOuoZ32nGegUP
        jvpjQp0z7BSKrtrwM9Q419s=
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRjCCAi6gAwIBAgIJAMfW+Aaz1FUxMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA4MDYxODI3
            MDBaFw0yNjA4MDYxOTI3MDBaMIGsMS0wKwYDVQQKEyQzNjBjMDA5Yi0xNTkyLTRi
            MjItYjYyMS1hZWFjZjA3ZjAxOWUxGjAYBgNVBAsMEUNPTExFQ1RPUl9TRVJWSUNF
            MUAwPgYDVQQDDDdDT0xMRUNUT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAw
            LTAwMDAtMDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxNDM5OTk2OTU2NjIzNDI2ODk3
            NzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHclVTc5Knjv7EAef5P0LPm2MHog
            7W68GAGqrLdDBombiJAbGKyecQK55Lf10H9y1/o1QpdIifhzXV8duQHjZjijgbcw
            gbQwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
            AjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQy9cXnv79gC15oCsx1lNvf2ryk8TAf
            BgNVHSMEGDAWgBQYx1QSrKz9wmq1mktIhdsPGBXklTA1BgNVHREELjAsghJjb2xs
            ZWN0b3Iuc3RhY2tyb3iCFmNvbGxlY3Rvci5zdGFja3JveC5zdmMwDQYJKoZIhvcN
            AQELBQADggEBAF9sRwwIKXQ1wbGUD7IdFwvZRt6+hIGbWRnaFqP8XJgyeFA3r41J
            iqua0ul//oH74IzuYeKA4wCjXHj8myMYlv6L6LQOKNzj3wlBafCH+zucksTUrhfn
            DRLQMJFzkvcWHP0DVbYUT4zvAfOnwng16eItL4x1Fg3BgpY3FjZKsIWA2gIPnHFG
            K4MJTF5hfNRtJTMteQ2lpSukTTzIzNX2RsctrymE8zk9yB/rnVL3aNU/3vW3tbjY
            UT3yElncfKVUXrmn7BGZkDxaHRaNnWqO92dvTAE8BBmuaOdovtzkq655DQi6JsvM
            reV3NpqJkSaHCUgVOJQLB4q4XtHm5qn4vrk=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIFjbWuE0L/s5aVrMdDUSvJglm1DuqDkI+UA6ECAUMqK0oAoGCCqGSM49
            AwEHoUQDQgAEdyVVNzkqeO/sQB5/k/Qs+bYweiDtbrwYAaqst0MGiZuIkBsYrJ5x
            Arnkt/XQf3LX+jVCl0iJ+HNdXx25AeNmOA==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVzCCAj+gAwIBAgIJANyWimCLi2GQMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA4MDYxODI3
            MDBaFw0yNjA4MDYxOTI3MDBaMIGmMS0wKwYDVQQKEyQzNjBjMDA5Yi0xNTkyLTRi
            MjItYjYyMS1hZWFjZjA3ZjAxOWUxFzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0w
            OwYDVQQDDDRTRU5TT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
            MDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxNTg5NTA0NDA4MjExMzQwNTMyODBZMBMG
            ByqGSM49AgEGCCqGSM49AwEHA0IABMCzpTgMZ2G/IZjq8KuDv1x49FaU5fqcViV9
            qGOVYPQmbvyRYp4E0bjw3aklUDEO406sreS9y0H847Cd0DHKyB2jgc4wgcswDgYD
            VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
            HRMBAf8EAjAAMB0GA1UdDgQWBBSXlKO2VoRBaHq9Mxg5W9TxR94XDTAfBgNVHSME
            GDAWgBQYx1QSrKz9wmq1mktIhdsPGBXklTBMBgNVHREERTBDgg9zZW5zb3Iuc3Rh
            Y2tyb3iCE3NlbnNvci5zdGFja3JveC5zdmOCG3NlbnNvci13ZWJob29rLnN0YWNr
            cm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEA0A7H973iLMoTwBfy8kKG81J8eNqY
            H3S7ykwnWUaHk8yScRTq9OnAcJf9yf9bi7Ugr7wtwdVFXYLGiKa1wVS+sQSjVUc2
            O4nGeX2d2t44RqIqy5Q81q8rMnUpZhERFHh9UzerQX+URyZUPSZ3hBAIia4oPD0f
            1DnIK/WFeMXy3YB62sNp3VMU6e6rbkqnma2CMeg5gCFmnpaIOkBpHPLi0L51ifuC
            LJcaHG7DkOmDCfqfnfHGTqGpWw7AHlmL9+afMhs2rMXjdE9c3ZaRISbOfC5r1Szq
            qCbisTiAtaQrIe1c74FnA/JXFaraSFFmNZdMZ2UD39Elqjri1wi6v8cGGw==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIB60ABFfd9oYrhA/enWFMTwMjKz40rrgMOcwmxBJwnt8oAoGCCqGSM49
            AwEHoUQDQgAEwLOlOAxnYb8hmOrwq4O/XHj0VpTl+pxWJX2oY5Vg9CZu/JFingTR
            uPDdqSVQMQ7jTqyt5L3LQfzjsJ3QMcrIHQ==
            -----END EC PRIVATE KEY-----
