# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1746823475  nanos:841195393
#   expiresAt: seconds:1778359500
#   id:        d1d85280-cdbd-4edd-b65a-c8468999d47d
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZjCCAk6gAwIBAgIJALFt1qp3POzLMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA1MDkxOTQ1
            MDBaFw0yNjA1MDkyMDQ1MDBaMIG8MS0wKwYDVQQKEyRkMWQ4NTI4MC1jZGJkLTRl
            ZGQtYjY1YS1jODQ2ODk5OWQ0N2QxIjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9M
            X1NFUlZJQ0UxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAw
            MDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTI3
            ODUxMTA5NDQ4MDc5NzIwNDMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ3MHCJ
            s9Bex5YOmr3UOdlU9h/5ZJ5zXzX8pJMCfObQaB4L7yuoPe0k6lpo4qjtMDigX/hg
            eY9admxLtUDxDK4Do4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
            BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQURFgT+GNk
            i8BYy5kTDwEW265icmEwHwYDVR0jBBgwFoAU8KjqRnW5x7qx7a6pu6rN6jbts/0w
            RQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lv
            bi1jb250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAsyi6IuFZ
            nolyL6f55Nux2khCcGOCu3pC7wDI1vCXBrexbdAs78yyYIt3tSPU8Gpxtrn7V2NV
            QBFNb7m7GhrX/e/EVDN/o+AIgJdR/oxlLHVeNtgJLOOeHImMiTtQeM1l6Tz0Jz0s
            hSKhI4LKuYgIWUnvKUZcDFkkx6rtSHlyWVPUU0hFRPTrAL92zR5arGo1cbhIX3c2
            VUJ81gpvWcvQLrvPDF4/BeCbpOK4Xz9lBqIAwiEoS4bahfhKAUGHTzin220hUVWX
            xQh/+y9n3lLTo41OHRI0eIfoMla/BbSmQ7Wan6UsZM5zgmM+YuhY3hQcQHFU6YgF
            qR9A2cChpMe+mA==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIBGeanV67vlL0A9XH5GXdyPhTxmZ5wDjqki5uFgLyTwqoAoGCCqGSM49
            AwEHoUQDQgAENzBwibPQXseWDpq91DnZVPYf+WSec181/KSTAnzm0GgeC+8rqD3t
            JOpaaOKo7TA4oF/4YHmPWnZsS7VA8QyuAw==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPTCCAiWgAwIBAgIQAS0dm5UffiwpDE9FjXXGtTANBgkqhkiG9w0BAQsFADAp
        MScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjUw
        NTA5MjAzNDQzWhcNMzAwNTA4MjAzNDQzWjApMScwJQYDVQQDEx5TdGFja1JveCBD
        ZXJ0aWZpY2F0ZSBBdXRob3JpdHkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
        AoIBAQDuNknFYt8SpbvMv2hckeRJnmJZ6yrT6p5jnaupTYwRu0UdXRluMsMDjS9n
        OcW/GLvh2vTJN1w6e8QSiJH/yfpDu4FdnXCKXKyvV+Vyu4suzLdq8nAS/9prnVkH
        w+s8ArQu9+hKU6YbqoffXznUdhaMeg9ht7zIZLzS5oSeddt6mpK/++p3kPdg2iAB
        0oESBHh+n196WZeR7s6f09OAAnzlQBXdvCKOrwDy/WxXI/T60YPa5L+dJGTQBWO5
        2hA28pchLQu1meAeu8qUYrCPyaH1Q4qHPvfomwFVED78cvNIjar3GtqDMOHBvRlZ
        CqMo8W4TNerSL4L2MJvnHfrvHvSZAgMBAAGjYTBfMA4GA1UdDwEB/wQEAwICpDAd
        BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAd
        BgNVHQ4EFgQU8KjqRnW5x7qx7a6pu6rN6jbts/0wDQYJKoZIhvcNAQELBQADggEB
        AME61ZToGuS1lYwzzAVbPrMxQgxkRENdHdnRrRPfu1qVVLS7ttCisAYGDFzJil17
        QYT9s6W8H2kPWn0wrh11URx4rR+3iFYixrGAzp06vw4o0KxM3W0XQkS6Wlxu4Qq9
        Cou0Xus6mUH9+H9MClF1K0uLrsCOa8gZUKIInPXN8OeFqDBLNmXryQiCR372nWDT
        JVeoI+wRM5Td555k7VAzFKucnFWcIryeYoaDBs8t34MR3OemzkK1vsmA/1glp99D
        LXfuxHFlSF1JdDq6cpmIqQkSHF5bEtM+QYULNLNwIXixE1Zk+6mxXt4+J51HCuBs
        Yq5mb/xv95UR17pFBbJlnKg=
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDQzCCAiugAwIBAgIIAeWoNhfZ+f4wDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDUwOTE5NDUw
            MFoXDTI2MDUwOTIwNDUwMFowgaoxLTArBgNVBAoTJGQxZDg1MjgwLWNkYmQtNGVk
            ZC1iNjVhLWM4NDY4OTk5ZDQ3ZDEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxGzAZBgNVBAUTEjEzNjcwMDMxMzk4NjUyOTc5MDBZ
            MBMGByqGSM49AgEGCCqGSM49AwEHA0IABNLck7VW1827dl/MOg4dJ1bzsuIIjkHX
            +GjsGEV2laLXpTMligrU/xUlzZ69wi0E7jrZWSxAKScKNxHMzrGm3pGjgbcwgbQw
            DgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBR0o9uqvvxHxy697ysgouYtVZMlnTAfBgNV
            HSMEGDAWgBTwqOpGdbnHurHtrqm7qs3qNu2z/TA1BgNVHREELjAsghJjb2xsZWN0
            b3Iuc3RhY2tyb3iCFmNvbGxlY3Rvci5zdGFja3JveC5zdmMwDQYJKoZIhvcNAQEL
            BQADggEBAAV/hhkjGipd9yyfy2uAsyXc+RTByIWK4HTAaUNiLfQI9Loy+kKRJ2PS
            SQsMWhdvbeSU5DZolEUrciP6jofRsHM8JyKeQe2jTKyfCUKApfm8/wYXArn7ML86
            BIPGbQGr+FbF6YL/zWUZIY2iO27xAu3lcmb6F4JfmxTZHzepTfX+mhFK0WmllBtL
            dhQaOUW0f2ZOmNVB0Wl+DqhgwcR3RA0iGM6ONLxBer8N9rbmESZP3hE0lzAmfzBp
            IjTBhlILuNM/EYK5EvJT6/RxoRHVh4xZherwmjXZIzmG5+KHenuVhgImu3UUz9Qa
            6mvBF1/8cqxiQbFBuh2oEW5PGQxwxp0=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIJUwCgHixLrXvOs4i7100vrg+KlFpwSrov/7guHdGNR9oAoGCCqGSM49
            AwEHoUQDQgAE0tyTtVbXzbt2X8w6Dh0nVvOy4giOQdf4aOwYRXaVotelMyWKCtT/
            FSXNnr3CLQTuOtlZLEApJwo3EczOsabekQ==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVjCCAj6gAwIBAgIJAIcwuxEijG2jMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTA1MDkxOTQ1
            MDBaFw0yNjA1MDkyMDQ1MDBaMIGlMS0wKwYDVQQKEyRkMWQ4NTI4MC1jZGJkLTRl
            ZGQtYjY1YS1jODQ2ODk5OWQ0N2QxFzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0w
            OwYDVQQDDDRTRU5TT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
            MDAwMDAwMDAwMDAwMRwwGgYDVQQFExM5NzQxNDkxNjc2MjcwODQ5NDQzMFkwEwYH
            KoZIzj0CAQYIKoZIzj0DAQcDQgAEhdXRnOGdkzyckgXNSebWpYQYvoHnQWtGLIoH
            jFdFYC8mK8LkUa4Jpq7ayoNsMTm7nkfCXYnVTqYLFAEpG3EVHaOBzjCByzAOBgNV
            HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1Ud
            EwEB/wQCMAAwHQYDVR0OBBYEFEksUuk/eI2RT6noodNjpvOoKynKMB8GA1UdIwQY
            MBaAFPCo6kZ1uce6se2uqbuqzeo27bP9MEwGA1UdEQRFMEOCD3NlbnNvci5zdGFj
            a3JveIITc2Vuc29yLnN0YWNrcm94LnN2Y4Ibc2Vuc29yLXdlYmhvb2suc3RhY2ty
            b3guc3ZjMA0GCSqGSIb3DQEBCwUAA4IBAQCogVjAw9f0kEUdZJWQUaSmuQlVPqD7
            X2t2GiY3PtO09ZAWGAYjeDv3WW1iQVydPoxK8bKlAZKfbSMnhIG19zcYULNDKAfo
            Tbkeft3e1vScdTCSDvvLIsdPpvr1X4zpL2fW5cePj3oS7BxnWtiWeD+Tg7GTgxu4
            dy6zs5ymMrrCl4f+ORWc6zu/wuRjD+kF5G3kB0M6oNtd0/lvGRQZSfTDitfARKF5
            1jWSXT+7uJ1l+t+C5pxIuvv2wvm9CGJ7y5hzuuvlek7pf0ugxzZNaKw74JKNM12i
            wrwYslyxLRleICXr/mgMYWfzTTfuHFhjk7/lxGpuhihTc26447NsTXvb
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIJ7hI695hTabAWdG4vOePiRzm+gHAk1Otj5TVOW9hbLmoAoGCCqGSM49
            AwEHoUQDQgAEhdXRnOGdkzyckgXNSebWpYQYvoHnQWtGLIoHjFdFYC8mK8LkUa4J
            pq7ayoNsMTm7nkfCXYnVTqYLFAEpG3EVHQ==
            -----END EC PRIVATE KEY-----
