# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1743075766 nanos:951961453
#   expiresAt: seconds:1774611780
#   id:        5728ccb0-5561-4413-bd48-5f268f2bf009
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZjCCAk6gAwIBAgIJAOx1h3KXimJgMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTAzMjcxMDQz
            MDBaFw0yNjAzMjcxMTQzMDBaMIG8MS0wKwYDVQQKEyQ1NzI4Y2NiMC01NTYxLTQ0
            MTMtYmQ0OC01ZjI2OGYyYmYwMDkxIjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9M
            X1NFUlZJQ0UxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAw
            MDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTcw
            Mzg2NzM2OTE0NjQ1ODk5MjAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATE0/Lf
            ScYOAsLQ3SzPN4NQRBMegfwccfEfJ5hMzWk+i7FWDhYStHmu5SdpfYbGpNFZYrc7
            T9+0SO3tm5FKmn4ro4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
            BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUQh+gm5vQ
            qAZiu+prYLE3sJx3C9UwHwYDVR0jBBgwFoAUuroZ9AjalZpSKPHMW77SDIjzxkMw
            RQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lv
            bi1jb250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEARfRpXyty
            gypv9Uo1qDcwrnwEd85BCoczMbRU9lE0w3OBNpE1d+Ry8opvUIPfWmrmRld2qmyz
            i/gqtmEySniEmoy3922Xx2Mhiz9Ax5ThOsasd4gbD+ZvjBTclCJsF5JCLyIKscMB
            /9ZfBKIf+cZJAcnrmHxY0I0cl3fH7a0bPSbQuEeDPuPETsPhMZ9lpiSVAFKu+qLm
            1RL2Ga5WR3c2vxdVCKW/dF5uhVHSwWrc7shQMXnupKN+3fWUaeKUC2DSW6eCpoVt
            tc7MlQmHx1g0+2tom2/U55mcrzFQpASG6qKvG4i4pbgSXJV52pq+Qv+odk4W3Igx
            tlmg/tp4moSMIA==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIIJfwYIhwbessElibr01AR+oQk1unb6kiOTwF03Iv634oAoGCCqGSM49
            AwEHoUQDQgAExNPy30nGDgLC0N0szzeDUEQTHoH8HHHxHyeYTM1pPouxVg4WErR5
            ruUnaX2GxqTRWWK3O0/ftEjt7ZuRSpp+Kw==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRAJ+ihii64WS9nUTe8ggb6bowDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1
        MDMyNzExMzIwOFoXDTMwMDMyNjExMzIwOFowKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEA2tFwQJXAQs9Ut5FTdhyXdsdXwK1dnjmgHheDI7kYuSqz4FALju2ckkdB
        gGAqV0QfWQ39KNrALma1cTQa9v2qh2l5KaERnHGXZmCetsKCJS9Lv9K+m8RMSbIr
        8NPZCiMo6dovicJNLMv++/umQiPqgf9jwpDxTDaJvnCTVyR9jcxwkdXB5zXF1OEN
        y+R49Fz0bRxM4239BvZ968wTKhYwRntFepSO5gn4UvMfjFXBqvgclZOfK6HuG+lE
        BdNm/2OBvVBslb4PV+5DF9EBGygCXkQtfSa232OazfdChWZm2YDGnTMkDRrT85/M
        u9JH0HKIv8ibJMUsGSEYVD/WpS+jTQIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFLq6GfQI2pWaUijxzFu+0gyI88ZDMA0GCSqGSIb3DQEBCwUAA4IB
        AQADbc0vWM6xR/z0o5SJeqfOhi40hie51lgIMGz+jKn1WF6TrNWx0QxGEDkehVH7
        GuoVvhfCSB1wU8foETbevnoEptTFM5PZcjx/aBBnq1dbe1sN8qO9ho4vsscbSsh2
        hJNGHWvEHGSDnW6YS1SEp0/q6zBnPcA4FWV2bv8UuFMGm1zOeI6uaxhGx7oRQONw
        rdTuiyWKjydDJ3q38gUkcBtZuYO72wcU6QNRTU+v/5qalgsW1S5Eh0aQRk9CNCaw
        nYrG9fZum4PlE2m4YMYeLk2ksUhaE/3podtV2ASW444nTk7sx0XlBxMjdv7yCKxK
        3igebj1yAN65YV+NXBD3BOBR
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIIPy4wOEEwrH4wDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDMyNzEwNDMw
            MFoXDTI2MDMyNzExNDMwMFowgasxLTArBgNVBAoTJDU3MjhjY2IwLTU1NjEtNDQx
            My1iZDQ4LTVmMjY4ZjJiZjAwOTEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzQ1NTI2MjkyOTE0ODgxNjA4OTQw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT7w+5rY31kr7QmtoEXHVXUBL0inNN/
            jw+OwOk8hXxQDlAXTvymnPAIwIda9xqFm7D4P6b8hbmnQ3I5ljZwmo0so4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU9kZF+xZ/hXimnDA/6kO4+T0jtGEwHwYD
            VR0jBBgwFoAUuroZ9AjalZpSKPHMW77SDIjzxkMwNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQCPo9GyD0sKsh8MqSn5UGsE4bep2UBHRws9xKU09dhhW0S/xg7o+PYC
            R+1H60er5Bd3sloEzQOxAtX/tLEw/JAAjxUvh325jY33DP9TswtrJ4Z9cSbpMDbT
            ghtitBOF6rCsNl27q5xljjgdKrqjKMIn+msnV4AjHo3e+Tl4rfQmDxDvCEeFuVtC
            g+lUhTMLFiWpNtNsX35xmGGyRTZh1jgZal9x9IbV/dk5H2iNdQCPEh7VnnBy3R20
            FZ1VIjy8C3jk4J6HtxJymUSQg+TJwaX5IR4XhFXdMCYrHUy7u4tHvPvKsY4790Bh
            BUhTbRkbIDGHteQQRUOreE5LHgbvsXwd
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIKUPKcr2zp5sHeofr0ThUSDlAPPVd/Y/BaNqUizBsi/koAoGCCqGSM49
            AwEHoUQDQgAE+8Pua2N9ZK+0JraBFx1V1AS9IpzTf48PjsDpPIV8UA5QF078ppzw
            CMCHWvcahZuw+D+m/IW5p0NyOZY2cJqNLA==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVzCCAj+gAwIBAgIJAKjpH8w5mEB4MA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNTAzMjcxMDQz
            MDBaFw0yNjAzMjcxMTQzMDBaMIGmMS0wKwYDVQQKEyQ1NzI4Y2NiMC01NTYxLTQ0
            MTMtYmQ0OC01ZjI2OGYyYmYwMDkxFzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0w
            OwYDVQQDDDRTRU5TT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
            MDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxMjE3MTI5NDQyOTk0NTU0NDgyNDBZMBMG
            ByqGSM49AgEGCCqGSM49AwEHA0IABHB8pUtaJ5TMUfF685n82cBWQLmsVaTcee7Y
            41gPXDrDn+75jnNVbx1Rx/GsYcGO5Hnq62Zj11tCxDoe5pUxkP6jgc4wgcswDgYD
            VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
            HRMBAf8EAjAAMB0GA1UdDgQWBBQyxRQbXzjY5Po2xkDzgCX07oSpSjAfBgNVHSME
            GDAWgBS6uhn0CNqVmlIo8cxbvtIMiPPGQzBMBgNVHREERTBDgg9zZW5zb3Iuc3Rh
            Y2tyb3iCE3NlbnNvci5zdGFja3JveC5zdmOCG3NlbnNvci13ZWJob29rLnN0YWNr
            cm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAdbUbZGL1rFDtNOk6IIH3zbqXorq6
            +4PYKJrHu98eTMGieO4Vz3/EnybrRznBrmk5iFNcmsZfaGtYWdAmZlhW7trLdD0f
            13EqRkJsQkwSYWFBw4ZUewi8sYQkrIEjVFqgmDO59HpH+fLV+qfrvZi2vxV9pLRm
            cWzNWRw/vlN/WxZjSw6ha5Fp1DdnTW9EzzoI4iUwEhSYiHCYnhoUaASGWg8sARoB
            WEqErfFnYIaLqBSP96VNCND8kV3cCsjP4p2A8FPqhvffmf5M+3D+q1UzGOLqKEXC
            VgC1aYkwNPoyoL2CgGni7fbpY8q1XsFZJGxadd9KJKxfKOwz65khYzg5nQ==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIBAsjQ01VKj8U69kutfaURC+TlVCT+PqobhNxdv3HmpUoAoGCCqGSM49
            AwEHoUQDQgAEcHylS1onlMxR8XrzmfzZwFZAuaxVpNx57tjjWA9cOsOf7vmOc1Vv
            HVHH8axhwY7keerrZmPXW0LEOh7mlTGQ/g==
            -----END EC PRIVATE KEY-----
