# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "hetzner-cluster"
#   createdAt: seconds:1746831300 nanos:82881673
#   expiresAt: seconds:1778367300
#   id:        933c8f39-0c39-4c93-ada7-af3589faf753
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZDCCAkygAwIBAgIIDzDdJ5etIMQwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDUwOTIxNTUw
            MFoXDTI2MDUwOTIyNTUwMFowgbsxLTArBgNVBAoTJDkzM2M4ZjM5LTBjMzktNGM5
            My1hZGE3LWFmMzU4OWZhZjc1MzEiMCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xf
            U0VSVklDRTFIMEYGA1UEAww/QURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAw
            MDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMRwwGgYDVQQFExMxMDk0
            NjE3ODcxNTY5MTk5MzAwMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEdjLBQvXY
            Qlj1OPkr9DkonsMaajKkd4KvoqiY1J3ljXBPEqCwm0jpqLVCnigyw6E0XnhBFG2L
            w1vJUrVeUAmuc6OBxzCBxDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
            BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFFHr56eVzt3k
            XXtcnKaAFp3FvF9KMB8GA1UdIwQYMBaAFFELeyYV9LmBS1jzlMJ78mRJVNgcMEUG
            A1UdEQQ+MDyCGmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94gh5hZG1pc3Npb24t
            Y29udHJvbC5zdGFja3JveC5zdmMwDQYJKoZIhvcNAQELBQADggEBAG9xEjwSH1Fu
            L+jXelPGsKe4oW2G71+i47VNlkS0t8ewZyd+nlC0HjF7C7RHBbyOdbz+ROH9a2Tb
            KrJi7OaNlQaT5pz033pqNMCEn5o0DHWIvTvJ6yLeHUgDQsFCbY00c06bthoCmrrw
            njoCJtn204KzCvJL8vHhkFCJgOLpP4A+nIXz2cb17JV/8v93WDak4g6QNsY7LNmC
            SZ8UBsnc0iEAWfanvPknIR+cLoVv+Zd9N2nvRWyYrjBWSrjol8zzGeUPh9R9eL7C
            c7boXBjj/kTPPZyE7WM84Px8xDa82+wgg/4sGoojwNVc3A6ijZNNYzvpVRvZ8JDg
            fz9EVj7P4T4=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIMvZH/Txx9UH172WJdoPRjnemyWEhiZIh31THLprJoz0oAoGCCqGSM49
            AwEHoUQDQgAEdjLBQvXYQlj1OPkr9DkonsMaajKkd4KvoqiY1J3ljXBPEqCwm0jp
            qLVCnigyw6E0XnhBFG2Lw1vJUrVeUAmucw==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPTCCAiWgAwIBAgIQAYzdWbqjULtHdfuIlo2CPTANBgkqhkiG9w0BAQsFADAp
        MScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjUw
        NTA5MjI1MjMzWhcNMzAwNTA4MjI1MjMzWjApMScwJQYDVQQDEx5TdGFja1JveCBD
        ZXJ0aWZpY2F0ZSBBdXRob3JpdHkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
        AoIBAQC6aIwueGnLGbnAvuFA4AMYtuVn+Iywx9dmf3dF3paEnP6154VsRDkVUNCi
        jTZZrEkSyKjquLZa/kDVH+6IbM8JBing7WHP6ZpXj6gA8nFv6zOUgNa6y9Ns3I+S
        XC296vnZWKqtycpLwl22Kej6c9ub9o8yb3+1Wgpgod05qJ8CQ9PRbgt7nR8xeXpO
        XMrdYEhvFvJIAgmJ/Nkfh0JfVYnNvbM47iOGZ/eavToz+oTB/UEN4QTDTttvyhzp
        3Mtq5OO1mpolOG08PhTzg+Pb1rY0xM6ttB3lW+3H/B8rRtWNWFPVXtWzd8YWZtbs
        EkJ9ObM00AxlmCzhb2Sh6SIoARpDAgMBAAGjYTBfMA4GA1UdDwEB/wQEAwICpDAd
        BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAd
        BgNVHQ4EFgQUUQt7JhX0uYFLWPOUwnvyZElU2BwwDQYJKoZIhvcNAQELBQADggEB
        ABHpf4UIHrlmy5AbA30xubXiQrHm3FLPfKxQJ8dnd4D9SLIfod9IxxEFIY/UP7wO
        CVF9XUWctqYHbVpiFiaWopkNsw3eAjDZX6OTsjQYC4AUBOzm5P5h2QZeGlIN9pn3
        vyxLlyfT7xsg/3RoAOqpCOBxaGSgKyEEftXdhD042fXlnLJY1+L26+Mb20ktvXvX
        degiugXbalzcErZXFk1QPTpZ60SLIPVc6YITm+LtlPr7BkJ5RB5Xo8XSQ2g2XG3V
        CyG1FgucANXTmvPrWmxzKHO6hGKRqt8cb5uqS3eBZPi8NoKJ219YGJU5qDOL/wa7
        8l06zUyl3PDhlbXswjJPK28=
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDQzCCAiugAwIBAgIICPLM4tq3wp0wDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDUwOTIxNTUw
            MFoXDTI2MDUwOTIyNTUwMFowgaoxLTArBgNVBAoTJDkzM2M4ZjM5LTBjMzktNGM5
            My1hZGE3LWFmMzU4OWZhZjc1MzEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxGzAZBgNVBAUTEjY0NDgwMjk3MTM3MTU1MzQzNzBZ
            MBMGByqGSM49AgEGCCqGSM49AwEHA0IABC1xtMGGJYC+JeqlSYZ1NxcZxTFjOPiv
            X2LZPe040/Qd1PHKmkbUGzgZYTODFMG+8rGamCL5vQOqbYbv5dPi1BWjgbcwgbQw
            DgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTLJcN8QkI0M5hyvhBzESUG6rU9bzAfBgNV
            HSMEGDAWgBRRC3smFfS5gUtY85TCe/JkSVTYHDA1BgNVHREELjAsghJjb2xsZWN0
            b3Iuc3RhY2tyb3iCFmNvbGxlY3Rvci5zdGFja3JveC5zdmMwDQYJKoZIhvcNAQEL
            BQADggEBAJz0e+O9CILSbcd3DCquy0hjO8d4kCPSSnBRa7UlztkD1Lz7UsWhAHwM
            D5Eo0cNDw9Ors5Nyf+9Pd3Xn8ZuWdJc5PvKLl8Mi6LVRfeDRNgkwMO+NiuIb4s9b
            ktX+jdEEawt2EM2pQcWtm2wR1OhQec59eRUchIUrROs8yB2ia1oVEj6IrdVqEUYy
            4nSz+CQNjJXR5wsQX0vSgU3ECw6yRoHTfujbZwKz8Uj9399DsQVaQeeoNgwMBpvt
            nz3sPdoGcQgINd91JGa2uTn/pMDNBIjR6lEvbxAIQKBuTt+Er2PXslXR5IZ9I9i7
            Rzqy6u/rUqCDlKSEJgzec924dUe4QAQ=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIL04+sjyrdC1vaR+cyBuKsxyCrfosSSLjGMTYBNC+DH2oAoGCCqGSM49
            AwEHoUQDQgAELXG0wYYlgL4l6qVJhnU3FxnFMWM4+K9fYtk97TjT9B3U8cqaRtQb
            OBlhM4MUwb7ysZqYIvm9A6pthu/l0+LUFQ==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVTCCAj2gAwIBAgIIT8lQAJgIBkcwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI1MDUwOTIxNTUw
            MFoXDTI2MDUwOTIyNTUwMFowgaUxLTArBgNVBAoTJDkzM2M4ZjM5LTBjMzktNGM5
            My1hZGE3LWFmMzU4OWZhZjc1MzEXMBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7
            BgNVBAMMNFNFTlNPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0w
            MDAwMDAwMDAwMDAxHDAaBgNVBAUTEzU3NDkyMTQzNjI3OTYwMzM2MDcwWTATBgcq
            hkjOPQIBBggqhkjOPQMBBwNCAATNjFeIUn962q8vMLkuMPuUTzxyAo+a+4NtGU4I
            MwiJ8v3uAuk7vp+KmUHqpAgFz0Q0Ee2akh9NOmI+RzlZtdrRo4HOMIHLMA4GA1Ud
            DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
            AQH/BAIwADAdBgNVHQ4EFgQUUh/ILutFP5Lt8Op+BKyKzw1njQMwHwYDVR0jBBgw
            FoAUUQt7JhX0uYFLWPOUwnvyZElU2BwwTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNr
            cm94ghNzZW5zb3Iuc3RhY2tyb3guc3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3Jv
            eC5zdmMwDQYJKoZIhvcNAQELBQADggEBAHsQI/sLRD87fv3hYdKP8hH6yWPoSv6c
            /OjDEvLG5dUG75iAEf7Khuhp3FxVOMnhxnfc4iCk2c3rwP25NqTAjLvdEUOPfS1w
            X5/TwrV6v/gjXGt2PZ0mIfLiIrVB91gUPckKQg8UXMFU2M74Cpnvh5xveC3A0AY3
            WKG8rJzPZPrv4pVNNJVqIHbY2MzVidzZ5c7YoMoU+GF6AzBMYNVGX8+YGbxkAso3
            zJJM/66i/b2K79hocE9SYRQDjNvsRjaDNMWc+U0gAdyOnpWRqBvTyRFv2Evwgeyw
            IFZlqUBrXex/1QsnfVLMIsvklr+GQRzQHOCTAjsnLREljslaAXfilWI=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIM4vWZWjUHvPvEfgiJslrEwczB0tcGRPOPCEqy9bX3QLoAoGCCqGSM49
            AwEHoUQDQgAEzYxXiFJ/etqvLzC5LjD7lE88cgKPmvuDbRlOCDMIifL97gLpO76f
            iplB6qQIBc9ENBHtmpIfTTpiPkc5WbXa0Q==
            -----END EC PRIVATE KEY-----
